### ISSUE TITLE
PermissionError when trying to analyze boot.img

### ISSUE THREAD

**Issue by OctoNezd** [postmarketOS/pmbootstrap#1066]
IRC Log:
```
<OctoNezd> also, I get command failed % mkdir -p /home/octo/.local/var/pmbootstrap/cache_http
<matt07211> ^ Same happend to me lastnight. Fix: take ownership of the files usig chown and make them RW with chmod
<ata2001[m]> octoenzd: what error/retcode
<OctoNezd> PermissionError: [Errno 13] Permission denied: '/home/octo/.local/var/pmbootstrap/log.txt'
```
Workaround:
```
<matt07211> chown octo:octo /home/octo/.local/var/pmbootstrap/
<matt07211> and
<matt07211> chmod -R 755 /home/octo/.local/var/pmbootstrap/
```
Log:
```
octo@ubuntu:~$ pmbootstrap log
Traceback (most recent call last):
  File "/usr/local/bin/pmbootstrap", line 26, in <module>
    sys.exit(pmb.main())
  File "/home/octo/pmbootstrap/pmb/__init__.py", line 35, in main
    pmb_logging.init(args)
  File "/home/octo/pmbootstrap/pmb/helpers/logging.py", line 86, in init
    setattr(args, "logfd", open(args.log, "a+"))
PermissionError: [Errno 13] Permission denied: '/home/octo/.local/var/pmbootstrap/log.txt'
```
Running on Ubuntu Server 17.10 in Oracle VM Virtualbox

**Comment by Matt07211** [comment]
Recreated this on Solus
```$ python -V
Python 2.7.13
$ python3 -V
Python 3.5.4
```
```$ ls -al ~
....
drwx------  4 matt07211 matt07211     4096 Jan  1 21:38  .local
....
```

and before running script.
```$ ls -l ~/.local/
total 4
drwx------ 30 matt07211 matt07211 4096 Jan  1 21:33 share```

Running of the script:
```$ ./pmbootstrap.py init
[21:37:22] Target device (either an existing one, or a new one for porting).
[21:37:22] Available (44): amazon-thor, asus-flo, asus-grouper, fairphone-fp2, google-glass, htc-ace, htc-bravo, huawei-angler, huawei-y530, lenovo-karate, lg-d285, lg-d855, lg-dory, lg-h815, lg-hammerhead, lg-lenok, lg-mako, motorola-osprey, motorola-titan, nokia-rx51, oneplus-bacon, oneplus-onyx, qemu-aarch64, qemu-amd64, qemu-vexpress, samsung-espresso10, samsung-i747m, samsung-i9003, samsung-i9070, samsung-i9100, samsung-i9305, samsung-i9505, samsung-maguro, samsung-n7100, samsung-s6500d, sony-amami, sony-aries, sony-castor-windy, sony-honami, sony-yuga, t2m-flame, teclast-x80pro, wiko-lenny3, xiaomi-ido
[21:37:22] Device [samsung-i9100]: samsung-g388f
[21:37:35] You are about to do a new device port for 'samsung-g388f'.
[21:37:35] Continue? (y/n) [y]: Y
[21:37:38] Device architecture (armhf/aarch64/x86_64) [armhf]: aarch64
[21:37:41] Who produced the device (e.g. LG)?
[21:37:41] Manufacturer: Samsung
[21:37:50] What is the official name (e.g. Google Nexus 5)?
[21:37:50] Name: Samsung xCover3
[21:37:56] Does the device have a hardware keyboard? (y/n) [n]: n 
[21:37:59] Does the device have a sdcard or other external storage medium? (y/n) [n]: y
[21:38:02] Which flash method does the device support?
[21:38:02] Flash method (fastboot/heimdall/0xffff/none) [fastboot]: heimdall
[21:38:06] Does the device use the "isolated recovery" or boot.img?
[21:38:06] <https://wiki.postmarketos.org/wiki/Deviceinfo_flash_methods#Isorec_or_bootimg.3F>
[21:38:06] Type (isorec/bootimg) [isorec]: bootimg
[21:38:09] You can analyze a known working boot.img file to automatically fill out the flasher information for your deviceinfo file. Either specify the path to an image or press return to skip this step (you can do it later with 'pmbootstrap bootimg_analyze').
[21:38:09] Path: /home/matt07211/Github/boot.img
[21:38:22] NOTE: You will be prompted for your sudo password, so we can set up a chroot to extract and analyze your boot.img file
[21:38:23] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/matt07211/.local/var/pmbootstrap/log.txt
[21:38:23] ERROR: Command failed: % mkdir -p /home/matt07211/.local/var/pmbootstrap/cache_http. Please try again.
[21:38:23] Path: ```

and after running script.
```$ ls -l ~/.local/
total 8
drwx------ 30 matt07211 matt07211 4096 Jan  1 21:33 share
drwxr-xr-x  3 root      root      4096 Jan  1 21:38 var```

This is fixable by taking owner ship of var/ and sub folders and allowing RW.

**Comment by ollieparanoid** [comment]
@OctoNezd, @Matt07211: Thanks a lot for the detailed bug report!

I think this is a `mkdir -p` we run with sudo in the bootimg analyze step before we created the work folder, hence the work folder is owned by root. If that was the case, the fix would be making sure that the work folder was created before we run that `mkdir -p`, and that it gets created as user.

(Does someone want to take this? Otherwise I'll fix it soon.)

**Comment by OctoNezd** [comment]
Tell me which file contains that command I will do a PR. I am not too good in finding stuff in big projects like this

**Comment by ollieparanoid** [comment]
That is very kind of you! `pmb/config/init.py` is the relevant file.

Actually we would need to ask for the `work` folder *before* we ask for the device, because we create the work folder with appropriate permissions right after we ask for the path (that is so we can make sure that it can be created in the given location).

https://github.com/postmarketOS/pmbootstrap/blob/bde1152fdd4aa342593db74465f0b42e9fb0d1e6/pmb/config/init.py#L204-L222


I think it should be fixed with:
* Moving `cfg["pmbootstrap"]["work"] = ask_for_work_path(args)` before asking for the device
* Setting `args.work` to the work path that was chosen in this function, so the device wizard uses the right folder. So the line changes to: `args.work = cfg["pmbootstrap"]["work"] = ask_for_work_path(args)`

All of this is guessing and need proper testing 😃

**Comment by ollieparanoid** [comment]
Actually I can make some time to fix this right now - and this should be fixed really soon since it hits all new users directly when they using `pmbootstrap` the first time to port a new device.
