### ISSUE TITLE
Unpacking kernel fails (can't cd to /home/user/....)

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#11]
I'm trying to port to the nexus 5 with the lineage os kernel. I made a copy from the nexus 4 kernel package and edited it for the nexus 5 with this repository: https://github.com/LineageOS/android_kernel_lge_hammerhead

The build fails before compiling because the CD command fails after unpacking the kernel source.

Build log:
```
(002316) [17:40:42] (native) build armhf/linux-lg-hammerhead-3.4.0-r3.apk
(002316) [17:40:42] (native) % rm -rf /home/user/build
(002316) [17:40:43] % sudo cp -r /home/martijn/Projects/Other/pmbootstrap/aports/linux-lg-hammerhead/ /home/martijn/.local/var/pmbootstrap/chroot_native/home/user/build
(002316) [17:40:43] (native) % chown -R user:user /home/user/build
(002316) [17:40:43] (native) % cd /home/user/build && su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d'
>>> linux-lg-hammerhead: Checking sanity of /home/user/build/APKBUILD...
>>> WARNING: linux-lg-hammerhead: No maintainer
>>> linux-lg-hammerhead: Cleaning temporary build dirs...
>>> linux-lg-hammerhead: Checking sha512sums...
1dae34efb7d2399073ca371c953aafd2ed503849.zip: OK
config-lg-hammerhead.armhf: OK
compiler-gcc6.h: OK
>>> linux-lg-hammerhead: Unpacking /var/cache/distfiles/1dae34efb7d2399073ca371c953aafd2ed503849.zip...
/usr/bin/abuild: cd: line 1: can't cd to /home/user/build/src/lg-kernel-hammerhead-1dae34efb7d2399073ca371c953aafd2ed503849
>>> ERROR: linux-lg-hammerhead: all failed
(002316) [17:40:50] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d'
(002316) [17:40:50] Run 'pmbootstrap log' for details.
(002316) [17:40:50] Traceback (most recent call last):
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 40, in core
    check=check)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/martijn/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 58, in main
    pmb.build.package(args, args.package, args.arch, args.force, False)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/build/package.py", line 105, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 48, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d'
```

APKBUILD:
```bash
_vendor=lg
_flavor=lg-hammerhead
_hash="1dae34efb7d2399073ca371c953aafd2ed503849"
_config="config-${_flavor}.armhf"

pkgname=linux-${_flavor}
pkgver=3.4.0
case $pkgver in
        *.*.*)  _kernver=${pkgver%.*};;
        *.*) _kernver=$pkgver;;
esac
pkgrel=3
arch="armhf"
pkgdesc="Nexus 5 kernel from LineageOS"
url="https://github.com/LineageOS/android_kernel_lge_hammerhead"
depends="postmarketos-mkinitfs"
makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev"
options="!strip !check !tracedeps"
install=
source="
        https://github.com/LineageOS/android_kernel_lge_hammerhead/archive/${_hash}.zip
        $_config
        compiler-gcc6.h
"
subpackages=""
license="GPL2"

_abi_release=${pkgver}
_carch="arm"
HOSTCC="${CC:-gcc}"
HOSTCC="${HOSTCC#${CROSS_COMPILE}}"

ksrcdir="$srcdir/${_vendor}-kernel-hammerhead-${_hash}"

prepare() {
        local _patch_failed=
        cd "$ksrcdir"

        # first apply patches in specified order
        for i in $source; do
                case $i in
                *.patch)
                        msg "Applying $i..."
                        if ! patch -s -p1 -N -i "$srcdir"/$i; then
                                echo $i >>failed
                                _patch_failed=1
                        fi
                        ;;
                esac
        done

        if ! [ -z "$_patch_failed" ]; then
                error "The following patches failed:"
                cat failed
                return 1
        fi

        # gcc6 support
        cp -v "$srcdir/compiler-gcc6.h" "$ksrcdir/include/linux/"

        mkdir -p "$srcdir"/build
        cp "$srcdir"/$_config "$srcdir"/build/.config || return 1
        make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
                silentoldconfig
}
this is so we can do: 'abuild menuconfig' to reconfigure kernel
menuconfig() {
        cd "$srcdir"/build || return 1
        make ARCH="$_carch" menuconfig
        cp .config "$startdir"/$_config
}

build() {
        cd "$srcdir"/build
        unset LDFLAGS
        make ARCH="$_carch" CC="${CC:-gcc}" \
                KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-Alpine" \
                || return 1
}

package() {
        install -Dm644 "$srcdir/build/arch/arm/boot/zImage" \
                "$pkgdir/boot/vmlinuz-$_flavor"

        install -D "$srcdir/build/include/config/kernel.release" \
                "$pkgdir/usr/share/kernel/$_flavor/kernel.release"
}


```

**Comment by ollieparanoid** [comment]
Looks like you posted the log twice instead of the APKBUILD, so I cant't tell exactly what is going wrong.
Anyway, at some point it tries to `cd` into the wrong folder. You can simply open a shell in the chroot and inspect the real folder structure, after your build failed:
```shell
pmbootstrap chroot
cd /home/user/build/
ls
cd src
ls
# ...
```
...and fix the cd command in the APKBUILD afterwards, that caused this error:
```
/usr/bin/abuild: cd: line 1: can't cd to /home/user/build/src/lg-kernel-hammerhead-1dae34efb7d2399073ca371c953aafd2ed503849
```

**Comment by MartijnBraam** [comment]
Thanks that fixed it. Now I got to fix the linux compile errors, love the android ecosystem /s
