### ISSUE TITLE
Support for Xiaomi Redmi 4A

### ISSUE THREAD

**Issue by dineshdb** [postmarketOS/pmbootstrap#1370]
I know you guys are working hard. Just wanted to let you know that recently kernel sources for Redmi 4A were released. It would be better if someone with deep knowledge in kernel sources could get their hand dirty. https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/riva-n-oss.

I love your work. Would like to contribute some day with code.

**Comment by PureTryOut** [comment]
I made a basic device package [here](https://github.com/postmarketOS/pmbootstrap/tree/device-xiaomi-rolex). Note that it's untested as I don't actually have this device, but in theory it should "just work" :tm:

Quick question, since this kernel seems to be also used for the Redmi 5 and Redmi 5A, is the Redmi 5 actually the Redmi **Note** 5? I can't find much about the regular Redmi 5... Note that merging the defconfigs of the 3 devices won't work as they use different touchscreen devices which have conflicting code ([producing a big list of errors](https://bpaste.net/show/d94ef5f8a631)).

**Comment by dineshdb** [comment]
@PureTryOut  I would love to but currently  that's my main device. Would see if I can arrange some other device. 

As far as I know Redmi 5 and Note 5 are different products. 
Glad to know it's being worked on.

**Comment by PureTryOut** [comment]
Note that if you use an sdcard and the device supports flashboot (which the Redmi 4A seems to do), you can try pmOS out without touching your normal installation.

```
pmbootstrap init #choose your device and whatever other settings you desire
pmbootstrap install --android-recovery-zip
pmbootstrap flasher --method adb sideload # make sure the device is booted into the recovery for this one
pmbootstrap flasher boot # fastboot mode here
```

**Comment by dineshdb** [comment]
Which device am I supposed to choose to build? I can't see anything similar to rolex or riva. This is my first time with pmOS. I'm trying to understand from the wiki. Detailed article or getting started links would be helpful. Thank you.

**Comment by dineshdb** [comment]
One more question: Does pmbootstrap work on arch linux? 
Error here: ``(native) % apk --no-progress add gcc-armhf g++-armhf ccache-cross-symlinks``

**Comment by dineshdb** [comment]
Got this error again:
```
Executing busybox-1.28.2-r0.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 160 MiB in 55 packages
(009544) [17:23:36] (buildroot_aarch64) % apk --no-progress add abuild build-base ccache
(009544) [17:28:36] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(009544) [17:28:36] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/dineshdb/.local/var/pmbootstrap/log.txt
(009544) [17:28:36] ERROR: Command failed: (buildroot_aarch64) % apk --no-progress add abuild build-base ccache
(009544) [17:28:36] Run 'pmbootstrap log' for details.
(009544) [17:28:36] See also: <https://postmarketos.org/troubleshooting>
(009544) [17:28:36] Traceback (most recent call last):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/run.py", line 69, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'env', '-i', '/usr/bin/sh', '-c', "CHARSET=UTF-8 HISTFILE='~/.ash_history' PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash TERM=xterm /usr/bin/chroot /home/dineshdb/.local/var/pmbootstrap/chroot_buildroot_aarch64 /bin/sh -c 'cd /;apk --no-progress add abuild build-base ccache'"]' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/frontend.py", line 208, in install
    pmb.install.install(args)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/install/_install.py", line 385, in install
    pmb.build.package(args, pkgname, args.deviceinfo["arch"])
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 424, in package
    skip_init_buildenv, src):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 173, in init_buildenv
    depends, built = build_depends(args, apkbuild, arch, strict)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 128, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 424, in package
    skip_init_buildenv, src):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 181, in init_buildenv
    pmb.build.init(args, suffix)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/init.py", line 38, in init
    build=False)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/chroot/apk.py", line 233, in install
    pmb.chroot.root(args, ["apk", "--no-progress"] + command, suffix)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/chroot/root.py", line 93, in root
    return pmb.helpers.run.core(args, cmd_sudo, msg, log, return_stdout, check)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/run.py", line 82, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_aarch64) % apk --no-progress add abuild build-base ccache

(012183) [18:07:38] % tail -f /home/dineshdb/.local/var/pmbootstrap/log.txt -n 60
(012183) [18:07:38] *** output passed to pmbootstrap stdout, not to this log ***
```

**Comment by PureTryOut** [comment]
Again, please run `pmbootstrap log` in a separate terminal while running the failing command and please paste that instead.

**Comment by dineshdb** [comment]
```
(020648) [19:57:38] *** (1/4) PREPARE NATIVE CHROOT ***
(020648) [19:57:38] (native) calculate depends of cryptsetup, util-linux, e2fsprogs, parted (pmbootstrap -v for details)
(020648) [19:57:39] *** (2/4) CREATE DEVICE ROOTFS ("xiaomi-rolex") ***
(020648) [19:57:39] (rootfs_xiaomi-rolex) calculate depends of musl, so:libc.musl-aarch64.so.1, busybox, /bin/sh, cmd:busybox, cmd:sh, alpine-baselayout, command:mkmntdirs, openrc, so:libeinfo.so.1, so:librc.so.1, cmd:openrc, cmd:openrc-run, cmd:rc, cmd:rc-service, cmd:rc-sstat, cmd:rc-status, cmd:rc-update, cmd:runscript, cmd:service, cmd:start-stop-daemon, cmd:supervise-daemon, alpine-conf, cmd:lbu, cmd:lbu_commit, cmd:lbu_exclude, cmd:lbu_include, cmd:lbu_status, cmd:lbu_update, cmd:setup-acf, cmd:setup-alpine, cmd:setup-apkcache, cmd:setup-apkrepos, cmd:setup-bootable, cmd:setup-disk, cmd:setup-dns, cmd:setup-gparted-desktop, cmd:setup-hostname, cmd:setup-interfaces, cmd:setup-keymap, cmd:setup-lbu, cmd:setup-mta, cmd:setup-ntp, cmd:setup-proxy, cmd:setup-sshd, cmd:setup-timezone, cmd:setup-xen-dom0, cmd:setup-xorg-base, cmd:uniso, cmd:update-conf, cmd:update-kernel, libressl2.6-libcrypto, so:libcrypto.so.42, libressl2.6-libssl, so:libssl.so.44, zlib, so:libz.so.1, apk-tools, cmd:apk, busybox-suid, cmd:bbsuid, busybox-initscripts, scanelf, musl-utils, cmd:getconf, cmd:getent, cmd:iconv, cmd:ldconfig, libc-utils, alpine-keys, alpine-base (pmbootstrap -v for details)
(020648) [19:57:40] (rootfs_xiaomi-rolex) % getent passwd user
user:x:1000:1000:Linux User,,,:/home/user:/bin/ash
(020648) [19:57:44] Build is necessary for package 'postmarketos-mkinitfs': Binary package out of date (binary: 0.6.1-r0, aport: 0.6.2-r0)
(020648) [19:57:44] (buildroot_aarch64) calculate depends of abuild, build-base, ccache (pmbootstrap -v for details)
(020648) [19:57:44] (buildroot_aarch64) % chmod -R a+rw /var/cache/distfiles
(020648) [19:57:44] (buildroot_aarch64) % cp /tmp/gzip_wrapper.sh /usr/local/bin/gzip
(020648) [19:57:44] (buildroot_aarch64) % chmod +x /usr/local/bin/gzip
(020648) [19:57:44] (buildroot_aarch64) % adduser pmos abuild
(020648) [19:57:44] (buildroot_aarch64) % sed -i -e s/^CLEANUP=.*/CLEANUP=''/ /etc/abuild.conf
(020648) [19:57:45] (buildroot_aarch64) calculate depends of libressl-dev (pmbootstrap -v for details)
(020648) [19:57:45] (buildroot_aarch64) install libressl-dev
(020648) [19:57:45] (buildroot_aarch64) % apk --no-progress add libressl-dev
WARNING: Ignoring /mnt/pmbootstrap-packages/aarch64/APKINDEX.tar.gz: No such file or directory
(1/1) Installing libressl-dev (2.6.4-r0)
OK: 181 MiB in 56 packages
(020648) [19:58:13] (native) calculate depends of gcc-aarch64, g++-aarch64, ccache-cross-symlinks (pmbootstrap -v for details)
(020648) [19:58:13] (native) install gcc-aarch64 g++-aarch64 ccache-cross-symlinks
(020648) [19:58:13] (native) % apk --no-progress add -u --virtual .pmbootstrap gcc-aarch64 g++-aarch64 ccache-cross-symlinks isl binutils-aarch64 libstdc++ gcc libc-dev ccache gmp libgcc binutils libgomp libatomic pkgconf mpc1 mpfr3 musl-dev binutils-libs
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory
(1/20) Installing gmp (6.1.2-r1)
(2/20) Installing isl (0.18-r0)
(3/20) Installing binutils-aarch64 (2.28-r3)
(4/20) Installing gcc-aarch64 (6.4.0-r7)
(5/20) Installing libgcc (6.4.0-r7)
(6/20) Installing libstdc++ (6.4.0-r7)
(7/20) Installing binutils-libs (2.28-r3)
(8/20) Installing binutils (2.28-r3)
(9/20) Installing libgomp (6.4.0-r7)
(10/20) Installing libatomic (6.4.0-r7)
(11/20) Installing pkgconf (1.4.2-r0)
(12/20) Installing mpfr3 (3.1.5-r1)
(13/20) Installing mpc1 (1.0.3-r1)
(14/20) Installing gcc (6.4.0-r7)
(15/20) Installing musl-dev (1.1.19-r1)
(16/20) Installing libc-dev (0.7.1-r0)
(17/20) Installing g++-aarch64 (6.4.0-r7)
(18/20) Installing ccache (3.4.1-r0)
(19/20) Installing ccache-cross-symlinks (1-r4)
(20/20) Installing .pmbootstrap (0)
Executing busybox-1.28.2-r0.trigger
OK: 311 MiB in 59 packages
(020648) [20:05:21] (native) % apk --no-progress add gcc-aarch64 g++-aarch64 ccache-cross-symlinks
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory
OK: 311 MiB in 59 packages
(020648) [20:06:21] (native) % apk --no-progress del .pmbootstrap
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory
(1/1) Purging .pmbootstrap (0)
OK: 311 MiB in 58 packages
(020648) [20:06:21] (buildroot_aarch64) calculate depends of distcc, arch-bin-masquerade (pmbootstrap -v for details)
(020648) [20:06:21] (buildroot_aarch64) install distcc arch-bin-masquerade
(020648) [20:06:21] (buildroot_aarch64) % apk --no-progress add -u --virtual .pmbootstrap distcc arch-bin-masquerade popt
WARNING: Ignoring /mnt/pmbootstrap-packages/aarch64/APKINDEX.tar.gz: No such file or directory
(1/3) Installing popt (1.16-r7)
(2/3) Installing distcc (3.1-r12)
Executing distcc-3.1-r12.pre-install
(3/3) Installing arch-bin-masquerade (1-r0)
Executing busybox-1.28.2-r0.trigger
OK: 182 MiB in 59 packages
(020648) [20:06:26] (buildroot_aarch64) % apk --no-progress add distcc arch-bin-masquerade
WARNING: Ignoring /mnt/pmbootstrap-packages/aarch64/APKINDEX.tar.gz: No such file or directory
OK: 182 MiB in 59 packages
(020648) [20:06:27] (buildroot_aarch64) % apk --no-progress del .pmbootstrap
WARNING: Ignoring /mnt/pmbootstrap-packages/aarch64/APKINDEX.tar.gz: No such file or directory
(1/37) Purging .pmbootstrap (0)
(2/37) Purging abuild (3.1.0-r4)
(3/37) Purging build-base (0.5-r1)
(4/37) Purging ccache (3.4.1-r0)
(5/37) Purging fakeroot (1.22-r0)
(6/37) Purging sudo (1.8.22-r2)
(7/37) Purging pax-utils (1.2.2-r1)
(8/37) Purging libressl (2.6.4-r0)
(9/37) Purging attr (2.4.47-r6)
(10/37) Purging tar (1.30-r0)
(11/37) Purging patch (2.7.6-r2)
(12/37) Purging lzip (1.20-r0)
(13/37) Purging curl (7.59.0-r0)
(14/37) Purging file (5.32-r0)
(15/37) Purging g++ (6.4.0-r7)
(16/37) Purging gcc (6.4.0-r7)
(17/37) Purging binutils (2.28-r3)
(18/37) Purging make (4.2.1-r2)
(19/37) Purging libc-dev (0.7.1-r0)
(20/37) Purging fortify-headers (0.9-r0)
(21/37) Purging libcap (2.25-r1)
(22/37) Purging libattr (2.4.47-r6)
(23/37) Purging libstdc++ (6.4.0-r7)
(24/37) Purging libcurl (7.59.0-r0)
(25/37) Purging ca-certificates (20171114-r0)
Executing ca-certificates-20171114-r0.post-deinstall
(26/37) Purging binutils-libs (2.28-r3)
(27/37) Purging libmagic (5.32-r0)
(28/37) Purging isl (0.18-r0)
(29/37) Purging libgomp (6.4.0-r7)
(30/37) Purging libatomic (6.4.0-r7)
(31/37) Purging mpc1 (1.0.3-r1)
(32/37) Purging mpfr3 (3.1.5-r1)
(33/37) Purging musl-dev (1.1.19-r1)
(34/37) Purging nghttp2-libs (1.31.0-r0)
(35/37) Purging libssh2 (1.8.0-r2)
(36/37) Purging libgcc (6.4.0-r7)
(37/37) Purging gmp (6.1.2-r1)
Executing busybox-1.28.2-r0.trigger
OK: 28 MiB in 22 packages
(020648) [20:06:28] (native) calculate depends of distcc, arch-bin-masquerade (pmbootstrap -v for details)
(020648) [20:06:28] (native) install distcc arch-bin-masquerade
(020648) [20:06:28] (native) % apk --no-progress add distcc arch-bin-masquerade
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory
(1/2) Installing arch-bin-masquerade (1-r0)
(2/2) Installing distcc (3.1-r12)
Executing distcc-3.1-r12.pre-install
Executing busybox-1.28.2-r0.trigger
OK: 312 MiB in 60 packages
(020648) [20:06:32] (native) start distccd (aarch64) on 127.0.0.1:33632
(020648) [20:06:32] (native) % busybox su pmos -c distccd --pid-file /home/pmos/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/pmos/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon
(020648) [20:06:32] (buildroot_aarch64) build aarch64/abuild-aarch64-qemu-workaround-3.1.0-r0.apk
(020648) [20:06:32] % sudo cp -r /home/dineshdb/Projects/pmbootstrap/aports/main/abuild-aarch64-qemu-workaround/ /home/dineshdb/.local/var/pmbootstrap/chroot_buildroot_aarch64/home/pmos/build
(020648) [20:06:32] (buildroot_aarch64) % chown -R pmos:pmos /home/pmos/build
(020648) [20:06:33] (buildroot_aarch64) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CCACHE_PREFIX=distcc CCACHE_PATH=/usr/lib/arch-bin-masquerade/aarch64:/usr/bin CCACHE_COMPILERCHECK=string:6.4.0-r7 DISTCC_HOSTS=127.0.0.1:33632 abuild -d -f
/bin/ash: abuild: not found
(020648) [20:06:33] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(020648) [20:06:33] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/dineshdb/.local/var/pmbootstrap/log.txt
(020648) [20:06:33] ERROR: Command failed: (buildroot_aarch64) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CCACHE_PREFIX=distcc CCACHE_PATH=/usr/lib/arch-bin-masquerade/aarch64:/usr/bin CCACHE_COMPILERCHECK=string:6.4.0-r7 DISTCC_HOSTS=127.0.0.1:33632 abuild -d -f
(020648) [20:06:33] Run 'pmbootstrap log' for details.
(020648) [20:06:33] See also: <https://postmarketos.org/troubleshooting>
(020648) [20:06:33] Traceback (most recent call last):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/run.py", line 69, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'env', '-i', '/usr/bin/sh', '-c', 'CHARSET=UTF-8 HISTFILE=\'~/.ash_history\' PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash TERM=xterm /usr/bin/chroot /home/dineshdb/.local/var/pmbootstrap/chroot_buildroot_aarch64 /bin/sh -c \'cd /home/pmos/build;busybox su pmos -c \'"\'"\'CARCH=aarch64 SUDO_APK=\'"\'"\'"\'"\'"\'"\'"\'"\'abuild-apk --no-progress\'"\'"\'"\'"\'"\'"\'"\'"\' CCACHE_PREFIX=distcc CCACHE_PATH=/usr/lib/arch-bin-masquerade/aarch64:/usr/bin CCACHE_COMPILERCHECK=string:6.4.0-r7 DISTCC_HOSTS=127.0.0.1:33632 abuild -d -f\'"\'"\'\'']' returned non-zero exit status 127.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/frontend.py", line 208, in install
    pmb.install.install(args)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/install/_install.py", line 385, in install
    pmb.build.package(args, pkgname, args.deviceinfo["arch"])
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 424, in package
    skip_init_buildenv, src):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 173, in init_buildenv
    depends, built = build_depends(args, apkbuild, arch, strict)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 128, in build_depends
    if package(args, depend, arch, strict=strict):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 424, in package
    skip_init_buildenv, src):
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 181, in init_buildenv
    pmb.build.init(args, suffix)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/init.py", line 91, in init
    pmb.build.qemu_workaround_aarch64(args, suffix)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/qemu_workaround_aarch64.py", line 33, in qemu_workaround_aarch64
    skip_init_buildenv=True)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 429, in package
    suffix, src)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/build/_package.py", line 365, in run_abuild
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build", env=env)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/chroot/user.py", line 46, in user
    auto_init, return_stdout, check)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/chroot/root.py", line 93, in root
    return pmb.helpers.run.core(args, cmd_sudo, msg, log, return_stdout, check)
  File "/home/dineshdb/Projects/pmbootstrap/pmb/helpers/run.py", line 82, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_aarch64) % cd /home/pmos/build; busybox su pmos -c CARCH=aarch64 SUDO_APK='abuild-apk --no-progress' CCACHE_PREFIX=distcc CCACHE_PATH=/usr/lib/arch-bin-masquerade/aarch64:/usr/bin CCACHE_COMPILERCHECK=string:6.4.0-r7 DISTCC_HOSTS=127.0.0.1:33632 abuild -d -f
```

**Comment by PureTryOut** [comment]
The error we need is just above the `^^^^^^^^^` line, so `/bin/ash: abuild: not found` in this case. It's unrelated to this issue, so please make a new issue for it and report your system setup, as I recall this having something to do with the filesystem being used by the host (although I might be wrong here).
