### ISSUE TITLE
ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CC=armv6-alpine-linux-muslgnueabihf-gcc CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'

### ISSUE THREAD

**Issue by Qwertie-** [postmarketOS/pmbootstrap#14]
I am currently trying to port pm to a new device but when I run `./pmbootstrap.py build linux-asus-grouper --arch=armhf` I get 

`[10:55:42] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CC=armv6-alpine-linux-muslgnueabihf-gcc CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'`

There is no such directory build in /home/user which is likely why its failing.

**Comment by ollieparanoid** [comment]
The `/home/user/...` path is inside the `native` chroot, as indicated by the `(native)` at the start of the command.
*Could you post the end of the logfile?* Whenever a command fails, there are two python stack traces (sorry for that, I'd rather have one, patches welcome) and above that is the actual output of the command, that has failed.

Thanks for trying out pmbootstrap!

**Comment by dzervas** [comment]
Here is the log (I think we have the same problem):
```
make[4]: Nothing to be done for 'install-data-am'.
make[4]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[3]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[2]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libstdc++-v3'
make[2]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make  install-recursive
make[3]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[4]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
true  DO=all multi-do # make
make[5]: Entering directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
true  DO=install multi-do # make
make[5]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[4]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[3]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[2]: Leaving directory '/home/user/build/src/build-cross-final/armv6-alpine-linux-muslgnueabihf/libvtv'
make[1]: Leaving directory '/home/user/build/src/build-cross-final'
/usr/bin/abuild: line 2356: /home/user/build/pkg/gcc-armhf/usr/share/gdb/python/auto-load/usr/armv6-alpine-linux-muslgnueabihf/lib/: Permission denied
>>> ERROR: gcc-armhf*: package failed
>>> ERROR: gcc-armhf: all failed
(018812) [05:01:11] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
(018812) [05:01:11] Run 'pmbootstrap log' for details.
(018812) [05:01:11] Traceback (most recent call last):
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/dzervas/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=x86_64 abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 58, in main
    pmb.build.package(args, args.package, args.arch, args.force, False)
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/build/package.py", line 70, in package
    "ccache-cross-symlinks"])
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/chroot/apk.py", line 48, in install
    pmb.build.package(args, package, arch)
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/build/package.py", line 105, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/home/dzervas/Lab/android/pmbootstrap/pmb/helpers/run.py", line 48, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
```

**Comment by Qwertie-** [comment]
Here is what I got
```

>>> linux-asus-grouper: Checking sanity of /home/user/build/APKBUILD...
>>> WARNING: linux-asus-grouper: No maintainer
>>> linux-asus-grouper: Cleaning temporary build dirs...
>>> linux-asus-grouper: Checking sha512sums...
953e26f2709dfe0c185c3c99c50b0c9d56d473a4.zip: OK
config-asus-grouper.armhf: OK
compiler-gcc6.h: OK
gpu-msm-fix-gcc5-compile.patch: OK
>>> linux-asus-grouper: Unpacking /var/cache/distfiles/953e26f2709dfe0c185c3c99c50b0c9d56d473a4.zip...
>>> linux-asus-grouper: Applying gpu-msm-fix-gcc5-compile.patch...
The text leading up to this was:
--------------------------
|source:
|https://github.com/ShinySide/HispAsian_Lollipop_G6/commit/b7756b6fc4bb728722b14d2dfdbaf1dc843812e9
|
|* These need to be static to avoid these errors:
|
|drivers/built-in.o: In function `.LANCHOR1':
|msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
|msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
|Makefile:877: recipe for target '.tmp_vmlinux1' failed
|make: *** [.tmp_vmlinux1] Error 1
|
|Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
|
|--- a/drivers/gpu/msm/kgsl_iommu.c
|+++ b/drivers/gpu/msm/kgsl_iommu.c
--------------------------
File to patch: 
Skip this patch? [y] 
2 out of 2 hunks ignored
>>> ERROR: linux-asus-grouper: The following patches failed:
gpu-msm-fix-gcc5-compile.patch
>>> ERROR: linux-asus-grouper: all failed
(028650) [14:31:31] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'
(028650) [14:31:31] Run 'pmbootstrap log' for details.
(028650) [14:31:31] Traceback (most recent call last):
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/user/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d\'"\'"\'\'']' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 58, in main
    pmb.build.package(args, args.package, args.arch, args.force, False)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/build/package.py", line 105, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/helpers/run.py", line 48, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'
```

**Comment by ollieparanoid** [comment]
@Qwertie-: The `gpu-msm-fix-gcc5-compile.patch` patch does not apply correctly to your kernel. It is `lg-mako` specific, so simply delete the file from the folder and remove it from the `sources` in the `APKBUILD`.
@dzervas: I'll treat your error in #19.

**Comment by Qwertie-** [comment]
That does seem to have solved an issue but it still fails

```
>>> linux-asus-grouper: Checking sanity of /home/user/build/APKBUILD...
>>> WARNING: linux-asus-grouper: No maintainer
>>> linux-asus-grouper: Cleaning temporary build dirs...
>>> linux-asus-grouper: Checking sha512sums...
953e26f2709dfe0c185c3c99c50b0c9d56d473a4.zip: OK
config-asus-grouper.armhf: OK
compiler-gcc6.h: OK
>>> linux-asus-grouper: Unpacking /var/cache/distfiles/953e26f2709dfe0c185c3c99c50b0c9d56d473a4.zip...
'/home/user/build/src/compiler-gcc6.h' -> '/home/user/build/src/android_kernel_asus_grouper-953e26f2709dfe0c185c3c99c50b0c9d56d473a4/include/linux/compiler-gcc6.h'
make: Entering directory '/home/user/build/src/android_kernel_asus_grouper-953e26f2709dfe0c185c3c99c50b0c9d56d473a4'
  GEN     /home/user/build/src/build/Makefile
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf --silentoldconfig Kconfig
*
* Restart config...
*
*
* IRQ subsystem
*
Support sparse irq numbering (SPARSE_IRQ) [N/y/?] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.

make[2]: *** [/home/user/build/src/android_kernel_asus_grouper-953e26f2709dfe0c185c3c99c50b0c9d56d473a4/scripts/kconfig/Makefile:34: silentoldconfig] Error 1
make[1]: *** [/home/user/build/src/android_kernel_asus_grouper-953e26f2709dfe0c185c3c99c50b0c9d56d473a4/Makefile:493: silentoldconfig] Error 2
make: *** [Makefile:130: sub-make] Error 2
make: Leaving directory '/home/user/build/src/android_kernel_asus_grouper-953e26f2709dfe0c185c3c99c50b0c9d56d473a4'
>>> ERROR: linux-asus-grouper: all failed
(010607) [09:30:35] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'
(010607) [09:30:35] Run 'pmbootstrap log' for details.
(010607) [09:30:35] Traceback (most recent call last):
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/user/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d\'"\'"\'\'']' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 58, in main
    pmb.build.package(args, args.package, args.arch, args.force, False)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/build/package.py", line 105, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/helpers/run.py", line 48, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CC=armv6-alpine-linux-muslgnueabihf-gcc CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- abuild -d'

```

**Comment by lawl** [comment]
Run `pmbootstrap linux-asus-grouper menuconfig` and answer the questions regarding the kernel config.

**Comment by Qwertie-** [comment]
Where do I get this information for menuconfig?

**Comment by MartijnBraam** [comment]
Mostly by knowing what kernel components do and what's needed for the device, most of the config should be in an existing defconfig file if you can find it for the nexus 7

**Comment by Qwertie-** [comment]
I found this but it doesn't seem to have the same options as the mako one

https://android.googlesource.com/kernel/tegra.git/+/android-tegra3-grouper-3.1-jb-fr2/arch/arm/configs/tegra3_android_defconfig

**Comment by ollieparanoid** [comment]
You can basically use the config, that comes with the kernel (looks like you already found the right one).

It doesn't need to have the same options, as in the `lg-mako` config.
If the building process doesn't run through, because of the config, run menuconfig once and accept the defaults (-> press return for every question).

Enabling `DEVTMPFS` in menuconfig is required to get touch screen support in Weston running (but you can do that later, the important part is getting the device to boot first.)

**Comment by kskarthik** [comment]
ollieparanoid pls help https://pastebin.mozilla.org/9023293

**Comment by ollieparanoid** [comment]
@kskarthik: Duplicate of #19 and already fixed. Just update pmboostrap. Please open up a new issue next time, if it does not relate to the current issue, thanks!

**Comment by Qwertie-** [comment]
@ollieparanoid I run menuconfig and kept all the defaults and still failing to build. I pushed all the current files to my fork.

**Comment by Qwertie-** [comment]
Ok I got it building now by adding the right config in and enabling devtmpfs in menuconfig
