### ISSUE TITLE
nokia-n900: pmbootstrap install fails for libcrypto.so.42

### ISSUE THREAD

**Issue by duncanguthrie** [postmarketOS/pmbootstrap#1408]
I'm attempting to run the installation program for the Nokia N900.

I first started by selecting the xfce4 interface. However, the problem is there for no interface at all:

`(002617) [15:31:03] (rootfs_nokia-n900) calculate depends of postmarketos-base, ttf-droid, device-nokia-n900 (pmbootstrap -v for details)`
`(002617) [15:31:04] NOTE: Run 'pmbootstrap pkgrel_bump --auto' to mark packages with outdated dependencies for rebuild. This will most likely fix this issue (soname bump?).`
`(002617) [15:31:04] ERROR: Could not find package 'so:libcrypto.so.42' in any aports folder or APKINDEX.`

I'm doubtful this is an issue due to the recent libressl library bump: I've tried running `pmbootstrap update && pmbootstrap index`; and I've tried running `pmbootstrap pkrel_bump --auto`, too, to no avail. I can build fine for qemu-vexpress. 

Unfortunately, pmbootstrap isn't particularly clear about what is causing the error. If this is a packaging issue, I'd expect it to show what depends on libcrypto.so.42, for instance.

**Comment by sicelo** [comment]
Thanks for opening the issue! I have been struggling with it for some time,
and had come to the conclusion that it  affected only me, as everyone else
on IRC seemed to not have issues.

**Comment by ollieparanoid** [comment]
I guess one of your locally built packages was built against `so:libcrypto.so.42` (which is one of the old libressl's sonames), and it has the same version (pkgver and pkgrel) as the upstream packages. This means, that `pmbootstrap` will your package instead of the one in the postmarketOS binary repository.

This should be fixed with:
* `pmbootstrap zap -p`
* rebase your branch on the official `master` branch

If it still does not work, can you try to reproduce this with the `master` branch?
And what do you get when specifying `pmbootstrap -v` for verbose mode? Then it should tell us where the `libcrypto.so.42` dependency comes from.

Sorry for the trouble, and thanks for opening this bug report! :+1:

**Comment by sicelo** [comment]
On Wed, Apr 11, 2018 at 06:38:12PM +0000, Oliver Smith wrote:
> I guess one of your locally built packages was built against `so:libcrypto.so.42` (which is one of the old libressl's sonames), and it has the same version (pkgver and pkgrel) as the upstream packages. This means, that `pmbootstrap` will your package instead of the one in the postmarketOS binary repository.
> 
> This should be fixed with:
> * `pmbootstrap zap -p`
> * rebase your branch on the official `master` branch

This has happened from a completely different machine, with the `master`
branch, so there is more to this.

> And what do you get when specifying `pmbootstrap -v` for verbose mode? Then it should tell us where the `libcrypto.so.42` dependency comes from.
`
(020680) [20:48:00] so:libexpat.so.1: provided by: expat
(020680) [20:48:00] expat: already found
(020680) [20:48:00] NOTE: APKINDEX not found, assuming no binary packages exist for that architecture: /home/sicelo/pmos/pmbootstrap/packages/armhf/APKINDEX.tar.gz
(020680) [20:48:00] so:libfreetype.so.6: provided by: freetype-2.9-r0 in /home/sicelo/pmos/pmbootstrap/cache_apk_armhf/APKINDEX.066df28d.tar.gz
(020680) [20:48:00] so:libfreetype.so.6: provided by: freetype
(020680) [20:48:00] freetype: depends on: so:libbz2.so.1,so:libc.musl-armhf.so.1,so:libpng16.so.16,so:libz.so.1
(020680) [20:48:00] NOTE: APKINDEX not found, assuming no binary packages exist for that architecture: /home/sicelo/pmos/pmbootstrap/packages/armhf/APKINDEX.tar.gz
(020680) [20:48:00] so:libc.musl-armhf.so.1: provided by: musl-1.1.19-r7 in /home/sicelo/pmos/pmbootstrap/cache_apk_armhf/APKINDEX.066df28d.tar.gz
(020680) [20:48:00] so:libc.musl-armhf.so.1: provided by: musl
(020680) [20:48:00] musl: already found
(020680) [20:48:00] NOTE: APKINDEX not found, assuming no binary packages exist for that architecture: /home/sicelo/pmos/pmbootstrap/packages/armhf/APKINDEX.tar.gz
(020680) [20:48:00] NOTE: Run 'pmbootstrap pkgrel_bump --auto' to mark packages with outdated dependencies for rebuild. This will most likely fix this issue (soname bump?).
(020680) [20:48:00] ERROR: Could not find package 'so:libcrypto.so.42' in any aports folder or APKINDEX.
(020680) [20:48:00] Run 'pmbootstrap log' for details.
(020680) [20:48:00] See also: <https://postmarketos.org/troubleshooting>
(020680) [20:48:00] Traceback (most recent call last):
  File "/home/sicelo/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/sicelo/pmbootstrap/pmb/helpers/frontend.py", line 179, in install
    pmb.install.install(args)
  File "/home/sicelo/pmbootstrap/pmb/install/_install.py", line 411, in install
    pmb.chroot.apk.install(args, install_packages, suffix)
  File "/home/sicelo/pmbootstrap/pmb/chroot/apk.py", line 195, in install
    packages_with_depends = pmb.parse.depends.recurse(args, packages, suffix)
  File "/home/sicelo/pmbootstrap/pmb/parse/depends.py", line 159, in recurse
    "' in any aports folder or APKINDEX.")
RuntimeError: Could not find package 'so:libcrypto.so.42' in any aports folder or APKINDEX.
`

You can let us know if more info is needed.

**Comment by ollieparanoid** [comment]
@sicelo: thanks! Yes, in fact I would need some more information. There should be a line above saying something like: `????: depends on: so:libcrypto.so.42`
Would it be possible to clear the log, and then attach the full log (you can attach it directly in the GitHub issue as file)? Log can be cleared with `pmbootstrap log -c`.

**Comment by sicelo** [comment]
Awesome, that gets us somewhere. Thanks @ollieparanoid 
Culprit is `uboot-tools` and that explains why so far it is only N900 with the problem. I'll attach the file shortly

**Comment by ollieparanoid** [comment]
Okay, `uboot-tools` is marked as [outdated](https://pkgs.alpinelinux.org/packages?name=uboot-tools&branch=edge) for `armhf`, but up to date for almost all other arches.

Unfortunately the `build-edge-armhf` didn't rebuild everything against the new `libressl` yet:
http://build.alpinelinux.org/

As a workaround, you can build `uboot-tools` against the current `libressl` yourself:
```
$ cd pmbootstrap
$ mkdir -p aports/_temp/uboot-tools
$ cd aports/_temp/uboot-tools
$ wget https://git.alpinelinux.org/cgit/aports/plain/testing/uboot-tools/APKBUILD
$ pmbootstrap build --arch=armhf uboot-tools
```

**Comment by sicelo** [comment]
Thank you for quick help! I tested this and it works fine.

**Comment by ollieparanoid** [comment]
You're welcome! Hopefully the new wiki page [Troubleshooting:dependencies](https://wiki.postmarketos.org/wiki/Troubleshooting:dependencies) will make it easier in the future.

**Comment by ollieparanoid** [comment]
Looks like I did not click the "reopen" button. Anyway, the binary package is up to date again in Alpine, so I'm removing it from our aports again. Now it's resolved :tada:
