### ISSUE TITLE
Flashing samsung-p4wifi with flash_kernel returns RuntimeError

### ISSUE THREAD

**Issue by aumars** [postmarketOS/pmbootstrap#1587]
Following step 4 of Samsung Galaxy Tab 10.1 at https://wiki.postmarketos.org/index.php?title=Samsung_Galaxy_Tab_10.1%22_(samsung-p4wifi)&oldid=3566. Running

```
$ ./pmbootstrap.py flasher flash_kernel
```

returns

```
Heimdall v1.4.2

Copyright (c) 2010-2017 Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
Claiming interface...
Setting up interface...

Initialising protocol...
Protocol initialisation successful.

Beginning session...

Some devices may take up to 2 minutes to respond.
Please be patient!

Session begun.

Downloading device's PIT file...
PIT file download successful.

ERROR: Partition "LNX" does not exist in the specified PIT.
Ending session...
Rebooting device...
Releasing device interface...

[17:29:41] ERROR: Command failed: (native) % heimdall flash --LNX /mnt/rootfs_samsung-p4wifi/boot/boot.img-samsung-p4wifi
Run 'pmbootstrap log' for details.
```

In the log:

```
(019623) [17:29:25] (rootfs_samsung-p4wifi) calculate depends of device-samsung-p4wifi (pmbootstrap -v for details)
(019623) [17:29:28] WARNING: Package 'mkbootimg' in your aports folder has version 2017.12.13-r0, but the binary package repositories already have version 2018.05.10-r0! See also: <https://postmarketos.org/warning-repo2>
(019623) [17:29:28] WARNING: Package 'postmarketos-mkinitfs' in your aports folder has version 0.6.5-r0, but the binary package repositories already have version 0.6.6-r0! See also: <https://postmarketos.org/warning-repo2>
(019623) [17:29:29] (rootfs_samsung-p4wifi) calculate depends of postmarketos-mkinitfs (pmbootstrap -v for details)
(019623) [17:29:29] (rootfs_samsung-p4wifi) calculate depends of  (pmbootstrap -v for details)
(019623) [17:29:29] (rootfs_samsung-p4wifi) mkinitfs samsung-p4wifi
(019623) [17:29:29] (rootfs_samsung-p4wifi) % mkinitfs -o /boot/initramfs-samsung-p4wifi 4.16.0
==> initramfs: creating /boot/initramfs-samsung-p4wifi
Scanning kernel module dependencies...
NOTE: ** modprobe warnings below can be ignored ** if your device does not run the
mainline kernel yet (most devices!) or if the related kernel options are enabled
with 'y' instead of 'm' (module).
==> kernel: appending device-tree tegra20-samsung_p3
==> initramfs: creating boot.img
==> initramfs: creating /boot/initramfs-samsung-p4wifi-extra
(019623) [17:29:35] Check kconfig: /home/pradana/pmbootstrap/aports/device/linux-samsung-p4wifi/config-samsung-p4wifi.armhf
(019623) [17:29:35] (native) flash kernel samsung-p4wifi
(019623) [17:29:35] (native) calculate depends of heimdall (pmbootstrap -v for details)
(019623) [17:29:36] (native) % heimdall_wait_for_device.sh
(019623) [17:29:36] *** output passed to pmbootstrap stdout, not to this log ***
(019623) [17:29:36] (native) % heimdall flash --LNX /mnt/rootfs_samsung-p4wifi/boot/boot.img-samsung-p4wifi
(019623) [17:29:36] *** output passed to pmbootstrap stdout, not to this log ***
(019623) [17:29:41] ERROR: Command failed: (native) % heimdall flash --LNX /mnt/rootfs_samsung-p4wifi/boot/boot.img-samsung-p4wifi
(019623) [17:29:41] See also: <https://postmarketos.org/troubleshooting>
(019623) [17:29:41] Traceback (most recent call last):
  File "/home/pradana/pmbootstrap/pmb/helpers/run.py", line 74, in core
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'env', '-i', '/usr/bin/sh', '-c', "CHARSET=UTF-8 HISTFILE='~/.ash_history' PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash TERM=xterm /usr/bin/chroot /home/pradana/.local/var/pmbootstrap/chroot_native /bin/sh -c 'cd /;heimdall flash --LNX /mnt/rootfs_samsung-p4wifi/boot/boot.img-samsung-p4wifi'"]' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pradana/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/pradana/pmbootstrap/pmb/helpers/frontend.py", line 183, in flasher
    pmb.flasher.frontend(args)
  File "/home/pradana/pmbootstrap/pmb/flasher/frontend.py", line 125, in frontend
    kernel(args)
  File "/home/pradana/pmbootstrap/pmb/flasher/frontend.py", line 46, in kernel
    pmb.flasher.run(args, "flash_kernel", flavor)
  File "/home/pradana/pmbootstrap/pmb/flasher/run.py", line 54, in run
    pmb.chroot.root(args, command, log=False)
  File "/home/pradana/pmbootstrap/pmb/chroot/root.py", line 93, in root
    return pmb.helpers.run.core(args, cmd_sudo, msg, log, return_stdout, check)
  File "/home/pradana/pmbootstrap/pmb/helpers/run.py", line 82, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % heimdall flash --LNX /mnt/rootfs_samsung-p4wifi/boot/boot.img-samsung-p4wifi
```

**Comment by Decatf** [comment]
Can you get the pit file from your device.
```shell
heimdall print-pit --no-reboot | tee mydevice.pit`
```

**Comment by aumars** [comment]
```
Entry Count: 16
Unknown 1: 1598902083
Unknown 2: 844251476
Unknown 3: 20302
Unknown 4: 17748
Unknown 5: 12337
Unknown 6: 0
Unknown 7: 0
Unknown 8: 0


--- Entry #0 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 80
Attributes: 2 (STL Read-Only)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 0
Partition Block Count: 1734
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: BOOTLOADER
Flash Filename: sboot.bin
FOTA Filename: 


--- Entry #1 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 81
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 1734
Partition Block Count: 312
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: TZSW
Flash Filename: tz.img
FOTA Filename: 


--- Entry #2 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 70
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 34
Partition Block Count: 16
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: PIT
Flash Filename: note10.pit
FOTA Filename: 


--- Entry #3 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 71
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 50
Partition Block Count: 2048
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: MD5HDR
Flash Filename: md5.img
FOTA Filename: 


--- Entry #4 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 1
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 8192
Partition Block Count: 8192
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: BOTA0
Flash Filename: -
FOTA Filename: 


--- Entry #5 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 2
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 16384
Partition Block Count: 8192
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: BOTA1
Flash Filename: -
FOTA Filename: 


--- Entry #6 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 3
Attributes: 5 (Read/Write)
Update Attributes: 5 (FOTA)
Partition Block Size/Offset: 24576
Partition Block Count: 40960
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: EFS
Flash Filename: efs.img
FOTA Filename: 


--- Entry #7 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 4
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 65536
Partition Block Count: 16384
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: PARAM
Flash Filename: param.bin
FOTA Filename: 


--- Entry #8 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 5
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 81920
Partition Block Count: 16384
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: BOOT
Flash Filename: boot.img
FOTA Filename: 


--- Entry #9 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 6
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 98304
Partition Block Count: 16384
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: RECOVERY
Flash Filename: recovery.img
FOTA Filename: 


--- Entry #10 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 7
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 114688
Partition Block Count: 65536
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: RADIO
Flash Filename: modem.bin
FOTA Filename: 


--- Entry #11 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 8
Attributes: 5 (Read/Write)
Update Attributes: 5 (FOTA)
Partition Block Size/Offset: 180224
Partition Block Count: 1638400
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: CACHE
Flash Filename: cache.img
FOTA Filename: 


--- Entry #12 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 9
Attributes: 5 (Read/Write)
Update Attributes: 5 (FOTA)
Partition Block Size/Offset: 1818624
Partition Block Count: 2867200
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: SYSTEM
Flash Filename: system.img
FOTA Filename: 


--- Entry #13 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 10
Attributes: 5 (Read/Write)
Update Attributes: 5 (FOTA)
Partition Block Size/Offset: 4685824
Partition Block Count: 1024000
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: HIDDEN
Flash Filename: hidden.img
FOTA Filename: 


--- Entry #14 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 11
Attributes: 5 (Read/Write)
Update Attributes: 1 (FOTA)
Partition Block Size/Offset: 5709824
Partition Block Count: 16384
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: OTA
Flash Filename: -
FOTA Filename: 


--- Entry #15 ---
Binary Type: 0 (AP)
Device Type: 2 (MMC)
Identifier: 12
Attributes: 5 (Read/Write)
Update Attributes: 5 (FOTA)
Partition Block Size/Offset: 5726208
Partition Block Count: 0
File Offset (Obsolete): 0
File Size (Obsolete): 0
Partition Name: USERDATA
Flash Filename: userdata.img
FOTA Filename: remained
```

**Comment by Decatf** [comment]
That is not a Galaxy Tab 10.1 (p4wifi). Maybe it's a Galaxy Note 10.1. I can't be certain which device but it's not a p4wifi device.

**Comment by aumars** [comment]
My mistake I'm using a Galaxy Note 10.1 (gt-n8013).
