### ISSUE TITLE
'Namespace' object has no attribute 'add'

### ISSUE THREAD

**Issue by yuvadm** [postmarketOS/pmbootstrap#162]
When attempting to flash a system partition on the mozilla flame I get:
```
$ ./pmbootstrap.py flasher flash_system
[19:33:39] *** (1/5) PREPARE NATIVE CHROOT ***
[19:33:40] *** (2/5) CREATE DEVICE ROOTFS (mozilla-flame) ***
[19:33:42] ERROR: 'Namespace' object has no attribute 'add'
[19:33:42] Run 'pmbootstrap log' for details.
[19:33:42] See also: <https://postmarketos.org/troubleshooting>
```

Full log:

```
(001940) [19:33:39] *** (1/5) PREPARE NATIVE CHROOT ***
(001940) [19:33:39] Calculate depends of packages ['cryptsetup', 'util-linux', 'e2fsprogs', 'parted'], arch: x86_64
(001940) [19:33:40] *** (2/5) CREATE DEVICE ROOTFS (mozilla-flame) ***
(001940) [19:33:40] (rootfs_mozilla-flame) % apk update
fetch https://nl.alpinelinux.org/alpine/edge/main/armhf/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/edge/community/armhf/APKINDEX.tar.gz
fetch https://nl.alpinelinux.org/alpine/edge/testing/armhf/APKINDEX.tar.gz
v3.6.0-1860-gacc627e27d [https://nl.alpinelinux.org/alpine/edge/main]
v3.6.0-1852-g8af106b18a [https://nl.alpinelinux.org/alpine/edge/community]
v3.6.0-1853-gc3fb7bc3bb [https://nl.alpinelinux.org/alpine/edge/testing]
OK: 10648 distinct packages available
(001940) [19:33:42] Calculate depends of packages dict_keys(['musl', 'so:libc.musl-armhf.so.1', 'busybox', 'alpine-baselayout', 'openrc', 'so:libeinfo.so.1', 'so:librc.so.1', 'alpine-conf', 'libressl2.5-libcrypto', 'so:libcrypto.so.41', 'libressl2.5-libssl', 'so:libssl.so.43', 'zlib', 'so:libz.so.1', 'apk-tools', 'busybox-suid', 'busybox-initscripts', 'scanelf', 'musl-utils', 'libc-utils', 'alpine-keys', 'alpine-base', 'busybox-extras', 'device-mapper-libs', 'so:libdevmapper.so.1.02', 'libuuid', 'so:libuuid.so.1', 'cryptsetup-libs', 'so:libcryptsetup.so.4', 'popt', 'so:libpopt.so.0', 'cryptsetup', 'lddtree', 'xz-libs', 'so:liblzma.so.5', 'kmod', 'so:libkmod.so.2', 'udev-init-scripts', 'eudev-libs', 'so:libudev.so.1', 'libblkid', 'so:libblkid.so.1', 'eudev', 'udev', 'libaio', 'so:libaio.so.1', 'json-c', 'so:libjson-c.so.2', 'ncurses-terminfo-base', 'ncurses-terminfo', 'ncurses-libs', 'ncurses-widec-libs', 'so:libformw.so.6', 'so:libmenuw.so.6', 'so:libncursesw.so.6', 'so:libpanelw.so.6', 'readline', 'so:libreadline.so.7', 'userspace-rcu', 'so:liburcu-bp.so.6', 'so:liburcu-cds.so.6', 'so:liburcu-common.so.6', 'so:liburcu-mb.so.6', 'so:liburcu-qsbr.so.6', 'so:liburcu-signal.so.6', 'so:liburcu.so.6', 'multipath-tools', 'so:libdmmp.so.0.1.0', 'so:libmpathcmd.so.0', 'so:libmpathpersist.so.0', 'so:libmultipath.so.0', 'postmarketos-mkinitfs', 'mkinitfs', 'linux-mozilla-flame', 'device-mozilla-flame']), arch: armhf
(001940) [19:33:42] % cd /home/yuval/dev/pmbootstrap/aports && git rev-parse --show-toplevel
/home/yuval/dev/pmbootstrap
(001940) [19:33:42] % cd /home/yuval/dev/pmbootstrap && git diff --name-only origin
aports/device-mozilla-flame/90-android-touch-dev.rules
aports/device-mozilla-flame/APKBUILD
aports/device-mozilla-flame/deviceinfo
aports/device-mozilla-flame/initfs-hook.sh
aports/device-mozilla-flame/profile.sh
aports/linux-mozilla-flame/APKBUILD
aports/linux-mozilla-flame/aeea3592a13bf12861943e44fc48f1f270941f8d.patch
aports/linux-mozilla-flame/compiler-gcc6.h
aports/linux-mozilla-flame/config-mozilla-flame.armhf
aports/linux-mozilla-flame/gpu-msm-fix-gcc5-compile.patch
(001940) [19:33:42] % cd /home/yuval/dev/pmbootstrap && git ls-files --others --exclude-standard
(001940) [19:33:42] ERROR: 'Namespace' object has no attribute 'add'
(001940) [19:33:42] Run 'pmbootstrap log' for details.
(001940) [19:33:42] See also: <https://postmarketos.org/troubleshooting>
(001940) [19:33:42] Traceback (most recent call last):
  File "./pmbootstrap.py", line 83, in main
    pmb.flasher.frontend(args)
  File "/home/yuval/dev/pmbootstrap/pmb/flasher/frontend.py", line 110, in frontend
    system(args)
  File "/home/yuval/dev/pmbootstrap/pmb/flasher/frontend.py", line 79, in system
    pmb.install.install(args, False)
  File "/home/yuval/dev/pmbootstrap/pmb/install/install.py", line 97, in install
    if args.add:
AttributeError: 'Namespace' object has no attribute 'add'
```

**Comment by ollieparanoid** [comment]
Are you running the latest code? Looks to me like rebasing to master was only done for some files, and now [this](https://github.com/postmarketOS/pmbootstrap/blob/56b9c2206e7f9380e7ce6f6c5350c6e95698e117/pmb/parse/arguments.py#L163) line is not present for example (that is where the "add" attribute should come from).

If `git rebase` fails you, I guess the easiest way would be to start with the current master, and copy the flame specific folders from aports.

**Comment by yuvadm** [comment]
@ollieparanoid oh, weird! Sure I'll try to recreate the branch manually.

**Comment by yuvadm** [comment]
@ollieparanoid well, it's there https://github.com/yuvadm/pmbootstrap/blob/device-mozilla-flame/pmb/parse/arguments.py#L163 note that i'm on my own branch

**Comment by ollieparanoid** [comment]
Thanks for checking! I'm probably wrong with this, but maybe functionality has changed with a different Python version? Which version do you have installed?
What happens, if you change `" added to the rootfs (e.g. 'vim,gcc')")` to `" added to the rootfs (e.g. 'vim,gcc')", dest="add")`?

**Comment by yuvadm** [comment]
@ollieparanoid I'm running Python 3.6.1, and that change didn't do much.

**Comment by ollieparanoid** [comment]
@yuvadm: thanks for testing! okay, I see the problem now. The `--add` argument only gets added for the `install` action, but you're running the `flasher` action (which executes `install`, because there's no image file yet!). This should be easy to fix by adjusting `pmb/parse/arguments.py´ to add the `--add` parameter to the `flasher` step, too.

Anyway, to work around this, please run `pmbootstrap install` first :)
