### ISSUE TITLE
install fails on configuring disk encryption

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#167]
Device: Sony amami

`./pmbootstrap.py install` fails on setting up disk encryption.

```
(002481) [22:49:16] Traceback (most recent call last):
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/helpers/run.py", line 50, in core
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', "unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/bart/.local/var/pmbootstrap/chroot_native sh -c 'cd /;cryptsetup luksFormat --use-urandom --cipher aes-cbc-plain64 -q /dev/installp2'"]' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 81, in main
    pmb.install.install(args)
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/install/install.py", line 117, in install
    pmb.install.format(args)
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/install/format.py", line 62, in format
    format_and_mount_root(args)
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/install/format.py", line 41, in format_and_mount_root
    "--cipher", args.cipher, "-q", device], log=False)
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/bart/Git/postmarketos-pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cryptsetup luksFormat --use-urandom --cipher aes-cbc-plain64 -q /dev/installp2
```

**Comment by ata2001** [comment]
Could you post the full output of the failed command (cryptsetup) too? It should be in the log, above the python traceback.

**Comment by PureTryOut** [comment]
Ended up being missing kernel support of the host system, entirely my own fault.
