### ISSUE TITLE
ERROR: 'Namespace' object has no attribute 'cmdline'

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#230]
When trying to run the following command:

`pmbootstrap flasher flash_system`

I get the following error:

```
[23:59:51] (native) flash system image
[23:59:51] ERROR: 'Namespace' object has no attribute 'cmdline'
[23:59:51] Run 'pmbootstrap log' for details.
[23:59:51] See also: <https://postmarketos.org/troubleshooting>
```

Traceback:

```
(003862) [00:02:55] Traceback (most recent call last):
  File "./pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/ata/Softwares/pmbootstrap/pmb/helpers/frontend.py", line 77, inflasher
    pmb.flasher.frontend(args)
  File "/home/ata/Softwares/pmbootstrap/pmb/flasher/frontend.py", line 119, in frontend
    system(args)
  File "/home/ata/Softwares/pmbootstrap/pmb/flasher/frontend.py", line 93, insystem
    pmb.flasher.run(args, "flash_system")
  File "/home/ata/Softwares/pmbootstrap/pmb/flasher/run.py", line 34, in run
    if args.cmdline:
AttributeError: 'Namespace' object has no attribute 'cmdline'
```

**Comment by ollieparanoid** [comment]
Thanks for the report, I'm on it!

**Comment by ata2001** [comment]
@ollieparanoid Thank you!
