### ISSUE TITLE
How to use pmbootstrap install

### ISSUE THREAD

**Issue by Roysten** [postmarketOS/pmbootstrap#4]
First of all thank you for this great project! :)

I managed to compile a kernel for a Samsung I9070 and now I would like to build the rest of PostmarketOS. I assume this has to be done using `pmbootstrap install`? That command does not work for me unfortunately:
```
(030397) [12:17:47] (buildroot_armhf) % chmod -R a+rw /var/cache/distfiles
(030397) [12:17:47] (buildroot_armhf) % cp /tmp/gzip_wrapper.sh /usr/local/bin/gzip
(030397) [12:17:47] (buildroot_armhf) % chmod +x /usr/local/bin/gzip
(030397) [12:17:47] (buildroot_armhf) % adduser user abuild
(030397) [12:17:47] (buildroot_armhf) % touch /var/local/pmbootstrap_chroot_build_init_done
(030397) [12:17:49] (buildroot_armhf) install wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev
(030397) [12:17:49] (buildroot_armhf) % apk --no-progress add wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev
ERROR: unsatisfiable constraints:
  so:libxcb.so.1 (missing):
    required by: cairo-1.14.8-r0[so:libxcb.so.1]
                 libx11-1.6.5-r0[so:libxcb.so.1]
                 libx11-1.6.5-r0[so:libxcb.so.1]
                 libx11-1.6.5-r0[so:libxcb.so.1]
                 libxkbcommon-0.6.1-r0[so:libxcb.so.1]
                 libxkbcommon-0.6.1-r0[so:libxcb.so.1]
                 cairo-tools-1.14.8-r0[so:libxcb.so.1]
                 libxkbcommon-0.6.1-r0[so:libxcb.so.1]
                 xcb-util-0.4.0-r1[so:libxcb.so.1]
                 cairo-1.14.8-r0[so:libxcb.so.1]
                 xcb-util-0.4.0-r1[so:libxcb.so.1]
                 cairo-1.14.8-r0[so:libxcb.so.1]
  libxcb-dev (missing):
    required by:
                 xcb-util-dev-0.4.0-r1[libxcb-dev]
                 xcb-util-dev-0.4.0-r1[libxcb-dev]
                 libx11-dev-1.6.5-r0[libxcb-dev]
                 xcb-util-dev-0.4.0-r1[libxcb-dev]
                 xcb-util-dev-0.4.0-r1[libxcb-dev]
                 libx11-dev-1.6.5-r0[libxcb-dev]
                 libx11-dev-1.6.5-r0[libxcb-dev]
                 xcb-util-dev-0.4.0-r1[libxcb-dev]
  pc:xcb (missing):
    required by: cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 libx11-dev-1.6.5-r0[pc:xcb]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 libx11-dev-1.6.5-r0[pc:xcb]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 libxkbcommon-dev-0.6.1-r0[pc:xcb]
                 libx11-dev-1.6.5-r0[pc:xcb]
                 libxkbcommon-dev-0.6.1-r0[pc:xcb]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb>=1.6]
                 libxkbcommon-dev-0.6.1-r0[pc:xcb]
  so:libxcb-render.so.0 (missing):
    required by:
                 cairo-1.14.8-r0[so:libxcb-render.so.0]
                 cairo-tools-1.14.8-r0[so:libxcb-render.so.0]
                 cairo-1.14.8-r0[so:libxcb-render.so.0]
                 cairo-1.14.8-r0[so:libxcb-render.so.0]
  so:libxcb-shm.so.0 (missing):
    required by:
                 cairo-1.14.8-r0[so:libxcb-shm.so.0]
                 cairo-1.14.8-r0[so:libxcb-shm.so.0]
                 cairo-1.14.8-r0[so:libxcb-shm.so.0]
  pc:xcb-render (missing):
    required by:
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
                 cairo-dev-1.14.8-r0[pc:xcb-render>=1.6]
  pc:xcb-shm (missing):
    required by: cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
                 cairo-dev-1.14.8-r0[pc:xcb-shm]
  so:libGL.so.1 (missing):
    required by: libva-1.8.1-r0[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 glu-9.0.0-r3[so:libGL.so.1]
                 libva-1.8.1-r0[so:libGL.so.1]
                 glu-9.0.0-r3[so:libGL.so.1]
  mesa-dev (missing):
    required by: libva-dev-1.8.1-r0[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
                 glu-dev-9.0.0-r3[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
                 glu-dev-9.0.0-r3[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
                 libva-dev-1.8.1-r0[mesa-dev]
  pc:gl (missing):
    required by: glu-dev-9.0.0-r3[pc:gl]
                 glu-dev-9.0.0-r3[pc:gl]
  so:libxcb-xkb.so.1 (missing):
    required by:
                 libxkbcommon-0.6.1-r0[so:libxcb-xkb.so.1]
                 libxkbcommon-0.6.1-r0[so:libxcb-xkb.so.1]
                 libxkbcommon-0.6.1-r0[so:libxcb-xkb.so.1]
  pc:xcb-xkb (missing):
    required by:
                 libxkbcommon-dev-0.6.1-r0[pc:xcb-xkb]
                 libxkbcommon-dev-0.6.1-r0[pc:xcb-xkb]
                 libxkbcommon-dev-0.6.1-r0[pc:xcb-xkb]
(030397) [12:17:49] ERROR: Command failed: (buildroot_armhf) % apk --no-progress add wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev
(030397) [12:17:49] Run 'pmbootstrap log' for details.
(030397) [12:17:49] Traceback (most recent call last):
  File "/mnt/data/pmos/pmbootstrap/pmb/helpers/run.py", line 40, in core
    check=check)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history DISTCC_FALLBACK=0  /usr/bin/chroot /mnt/data/pmos/work/chroot_buildroot_armhf sh -c 'cd /;apk --no-progress add wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev'"]' returned non-zero exit status 49.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 68, in main
    pmb.install.install(args)
  File "/mnt/data/pmos/pmbootstrap/pmb/install/install.py", line 89, in install
    ["device-" + args.device], suffix)
  File "/mnt/data/pmos/pmbootstrap/pmb/chroot/apk.py", line 48, in install
    pmb.build.package(args, package, arch)
  File "/mnt/data/pmos/pmbootstrap/pmb/build/package.py", line 62, in package
    package(args, depend, carch)
  File "/mnt/data/pmos/pmbootstrap/pmb/build/package.py", line 67, in package
    pmb.chroot.apk.install(args, apkbuild["makedepends"], suffix)
  File "/mnt/data/pmos/pmbootstrap/pmb/chroot/apk.py", line 59, in install
    suffix)
  File "/mnt/data/pmos/pmbootstrap/pmb/chroot/root.py", line 73, in root
    return_stdout, check)
  File "/mnt/data/pmos/pmbootstrap/pmb/helpers/run.py", line 48, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_armhf) % apk --no-progress add wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev
```
Is my assumption correct and do I use it correctly?

**Comment by ollieparanoid** [comment]
Great news with the kernel! Yes, your assumption is correct, that command builds the rest (and creates the rootfs image).

It looks like `apk` (Alpine's package manager, not to be confused with Android's app format) can't resolve `libxcb.so.1`, because it has just been updated upstream in Alpine Linux, and it has not been built yet for armhf:
https://pkgs.alpinelinux.org/contents?file=libxcb.so.1&path=&name=&branch=&repo=&arch=

(pmbootstrap uses the `edge` repository, because Wayland related programs are in the `testing` folder, which is only available in `edge` right now.)

The real solution here is, to wait until it gets build.

However, as a workaround, it might be possible to install the libxcb package from the v3.6 repository. This may introduce more problems if it works at all:
```
# open a shell inside the chroot, that needs the dependency (later this will probably also happen with the rootfs chroot for the device)
./pmbootstrap.py chroot --suffix=buildroot_armhf
# run inside the chroot
wget https://nl.alpinelinux.org/alpine/latest-stable/main/armhf/libxcb-1.12-r0.apk
apk add ./libxcb-1.12-r0.apk
```

**Comment by Roysten** [comment]
Ah I see, thank you! It seems only the apkbuild has changed, https://git.alpinelinux.org/cgit/aports/commit/?id=bc89232fbdea90b48a67cd2c0562092b102a56b2, so the 1.12 version should still be good.
