### ISSUE TITLE
Error in distcc build

### ISSUE THREAD

**Issue by yuvadm** [postmarketOS/pmbootstrap#420]
While attempting to test #416 I booted up a cloud VM (12GB RAM, 8 CPUs, Debian 9.1 x86_64) and ran a clean build, when I ran into this error, it happens on `master` branch as well:

```
[07:58:35] (native) index aarch64 repository
[07:58:35] (native) install distcc gcc-cross-wrappers
[07:58:36] (native) start distccd (armhf) on 127.0.0.1:33632
[07:58:36] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/user/.local/var/pmbootstrap/log.txt
[07:58:36] ERROR: Command failed: (native) % su user -c 'PATH=/usr/lib/gcc-cross-wrappers/armhf/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin distccd --pid-file /home/user/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/user/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon'
[07:58:36] Run 'pmbootstrap log' for details.
```

Log shows:

```
(030734) [07:58:36] (native) start distccd (armhf) on 127.0.0.1:33632
(030734) [07:58:36] (native) % su user -c 'PATH=/usr/lib/gcc-cross-wrappers/armhf/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin distccd --pid-file /home/user/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/user/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon'
(030734) [07:58:36] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(030734) [07:58:36] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/user/.local/var/pmbootstrap/log.txt
(030734) [07:58:36] ERROR: Command failed: (native) % su user -c 'PATH=/usr/lib/gcc-cross-wrappers/armhf/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin distccd --pid-file /home/user/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/user/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon'
(030734) [07:58:36] Run 'pmbootstrap log' for details.
(030734) [07:58:36] See also: <https://postmarketos.org/troubleshooting>
(030734) [07:58:36] Traceback (most recent call last):
  File "/home/user/pmbootstrap/pmb/helpers/run.py", line 45, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/user/.local/var/pmbootstrap/chroot_native sh -c \'cd /;su user -c \'"\'"\'PATH=/usr/lib/gcc-cross-wrappers/armhf/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin distccd --pid-file /home/user/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/user/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon\'"\'"\'\'']' returned non-zero exit status 102

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/user/pmbootstrap/pmb/helpers/frontend.py", line 113, in install
    pmb.install.install(args)
  File "/home/user/pmbootstrap/pmb/install/install.py", line 165, in install
    pmb.chroot.apk.install(args, install_packages, suffix)
  File "/home/user/pmbootstrap/pmb/chroot/apk.py", line 203, in install
    args, build, arch, package, packages_installed):
  File "/home/user/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/home/user/pmbootstrap/pmb/build/package.py", line 70, in package
    pmb.chroot.distccd.start(args, carch_buildenv)
  File "/home/user/pmbootstrap/pmb/chroot/distccd.py", line 118, in start
    pmb.chroot.user(args, cmdline)
  File "/home/user/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/user/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/user/pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % su user -c 'PATH=/usr/lib/gcc-cross-wrappers/armhf/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin distccd --pid-file /home/user/distccd.pid --listen 127.0.0.1 --allow 127.0.0.1 --port 33632 --log-file /home/user/distccd.log --jobs 9 --nice 19 --job-lifetime 60 --daemon'
```

Did I miss anything or is this a genuine bug?

**Comment by yuvadm** [comment]
After a reboot (`distccd` released?) this error doesn't happen anymore. Curious why it happened in the first place.

**Comment by ollieparanoid** [comment]
Does `pmbootstrap log_distccd` print anything useful, or is there anything in the distccd log regarding that crash (you will see the path in `pmbootstrap log` once you execute the other log command)?

If not, then I can't do anything to fix this and would close this until it appears again and we can reproduce it or at least have more information.

Thank you for making the report!

**Comment by yuvadm** [comment]
@ollieparanoid I recall the log only mentioned that distccd address is in use. Any idea why it would already be in use?

**Comment by ollieparanoid** [comment]
Well, then something else was already listening on the port. It could happen, when you run `pmbootstrap` twice with two different work folders, and without changing the `distccd` port (there's a parameter in `pmbootstrap` for that).

In case this happens again, you could see what is running on that port with `sudo netstat -peanut` ([see also](https://askubuntu.com/a/278455)).

*Closing until we have more information or can reproduce this.*

**Comment by yuvadm** [comment]
Yeah closing this issue is a good idea, I don't have any further information to conclude this is a bug.
