### ISSUE TITLE
RX-51. Install to sdcard fails

### ISSUE THREAD

**Issue by zenety** [postmarketOS/pmbootstrap#444]
Would love to bring back my N900 a bit back to life. I ran the pmbootstrap init for the rx51. Then ran the pmbootstrap install --sdcard /dev/sdb (in my case).

It errors out on.
`
pmbootstrap.py install --sdcard /dev/sdb[00:47:24] *** (1/5) PREPARE NATIVE CHROOT ***
[00:47:28] *** (2/5) CREATE DEVICE ROOTFS (nokia-rx51) ***
[00:47:28] Register qemu binfmt (arm)
[00:47:31] (native) build x86_64/binutils-armhf-2.28-r2.apk
[00:48:49] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/joost/.local/var/pmbootstrap/log.txt
[00:48:49] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
[00:48:49] Run 'pmbootstrap log' for details.
[00:48:49] See also: <https://postmarketos.org/troubleshooting>
`

The pmbootstrap log option gives me this:

```
mv -f .deps/tilegx.Tpo .deps/tilegx.Po
mv -f .deps/mips.Tpo .deps/mips.Po
make[4]: Leaving directory '/home/user/build/src/binutils-2.28/gold'
make[3]: *** [Makefile:941: all-recursive] Error 1
make[3]: Leaving directory '/home/user/build/src/binutils-2.28/gold'
make[2]: *** [Makefile:692: all] Error 2
make[2]: Leaving directory '/home/user/build/src/binutils-2.28/gold'
make[1]: *** [Makefile:6080: all-gold] Error 2
make[1]: Leaving directory '/home/user/build/src/binutils-2.28'
make: *** [Makefile:851: all] Error 2
>>> ERROR: binutils-armhf: all failed
(002898) [00:48:49] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(002898) [00:48:49] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/joost/.local/var/pmbootstrap/log.txt
(002898) [00:48:49] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
(002898) [00:48:49] Run 'pmbootstrap log' for details.
(002898) [00:48:49] See also: <https://postmarketos.org/troubleshooting>
(002898) [00:48:49] Traceback (most recent call last):
  File "/home/joost/Downloads/pmbootstrap/pmb/helpers/run.py", line 45, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /home/joost/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=x86_64 abuild -d\'"\'"\'\'']' returned non-zero exit status 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "./pmbootstrap.py", line 53, in main
    getattr(pmb.helpers.frontend, args.action)(args)
  File "/home/joost/Downloads/pmbootstrap/pmb/helpers/frontend.py", line 113, in install
    pmb.install.install(args)
  File "/home/joost/Downloads/pmbootstrap/pmb/install/install.py", line 183, in install
    pmb.chroot.apk.install(args, install_packages, suffix)
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 203, in install
    args, build, arch, package, packages_installed):
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/home/joost/Downloads/pmbootstrap/pmb/build/package.py", line 66, in package
    "ccache-cross-symlinks"])
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 203, in install
    args, build, arch, package, packages_installed):
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/home/joost/Downloads/pmbootstrap/pmb/build/package.py", line 62, in package
    pmb.chroot.apk.install(args, apkbuild["makedepends"], suffix)
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 203, in install
    args, build, arch, package, packages_installed):
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/home/joost/Downloads/pmbootstrap/pmb/build/package.py", line 106, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/joost/Downloads/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/joost/Downloads/pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=x86_64 abuild -d'
```

What is causing this? I am trying to build this on a Ubuntu 16.04 machine.

**Comment by MartijnBraam** [comment]
Looks like the build for `binutils-armhf` fails, which is a package in our own aports. Can you upload the full `log.txt` (which should be in the work dir you specified in the init step)

**Comment by zenety** [comment]
Thanks for the response. Here's the full log:

https://pastebin.com/29YA3Hk5

**Comment by ollieparanoid** [comment]
The actual compiler error is here:
```
g++ -DHAVE_CONFIG_H -I.  -I. -I./../include -I./../elfcpp -DLOCALEDIR="\"/usr/share/locale\"" -DBINDIR="\"/usr/bin\"" -DTOOLBINDIR="\"/usr/armv6-alpine-linux-muslgnueabihf/bin\"" -DTOOLLIBDIR="\"/usr/armv6-alpine-linux-muslgnueabihf/lib\""  -Os -fomit-frame-pointer -W -Wall    -Wstack-usage=262144 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -frandom-seed=script.o -I./../zlib -Os -fomit-frame-pointer -MT script.o -MD -MP -MF .deps/script.Tpo -c -o script.o script.cc
g++: internal compiler error: Killed (program cc1plus)
```

Some questions to debug this:
* In which environment are you running `pmbootstrap`? (Which Linux distribution, is it in a VM?)
* Did you run out of disk space or RAM?
* Do you have trouble compiling bigger programs on your host Linux distribution?

**Comment by zenety** [comment]
Accidentally gave the VM (Ubuntu 16.04) 1GB of ram. Works fine with 2gb+. Completely my fault.

Thanks for the quick solution.

**Comment by ollieparanoid** [comment]
@MartijnBraam yep, that would be good for the README.md! (Could you make a PR? :)
