### ISSUE TITLE
ERROR: Variable $PAGE_SIZE found in action boot for method fastboot, but the value for this variable is None!

### ISSUE THREAD

**Issue by Qwertie-** [postmarketOS/pmbootstrap#45]
I managed to compile and install for grouper but when I try and boot it I get this error.

```
(020707) [13:26:48] (native) boot asus-grouper kernel
(020707) [13:26:48] ERROR: Variable $PAGE_SIZE found in action boot for method fastboot, but the value for this variable is None!
(020707) [13:26:48] Run 'pmbootstrap log' for details.
(020707) [13:26:48] Traceback (most recent call last):
  File "./pmbootstrap.py", line 70, in main
    pmb.flasher.frontend(args)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/flasher/frontend.py", line 82, in frontend
    kernel(args)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/flasher/frontend.py", line 49, in kernel
    pmb.flasher.run(args, "boot", kernel, ramdisk)
  File "/media/user/665819ba-30ba-4a7a-a500-fa1ae9450d2b/Dev/pmbootstrap/pmb/flasher/run.py", line 53, in run
    " action " + action + " for method " + method + ","
RuntimeError: Variable $PAGE_SIZE found in action boot for method fastboot, but the value for this variable is None!
```

**Comment by lawl** [comment]
Did you set `deviceinfo_flash_pagesize` in your `deviceinfo` file?

**Comment by Qwertie-** [comment]
I have not, 
I took a look in https://github.com/postmarketOS/pmbootstrap/wiki/How-to-find-device-specific-information but it seems lineageOS has no builds for my device despite having the kernel copied over from cyanogen mod :L

**Comment by MartijnBraam** [comment]
The pagesize is most likely 2048, fastboot will complain if you set it wrong
