### ISSUE TITLE
sdcard format fails during install, unable to detect new partitions

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#475]
Ugh, ok a new error has shown up occasionally when trying to do `pmbootstrap install --sdcard=/dev/sdX`. 

What's weird about this one is that if I immediately do a `ls /dev/sdc*` then I see all of the partitions there.

```

(023210) [22:01:22] *** (3/5) PREPARE INSTALL BLOCKDEVICE ***           
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/var/cache/distfiles                          
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/var/cache/apk                                
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/proc                                         
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/packages/user                      
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/git                                
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/.ccache                            
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/.abuild                            
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/etc/apk/keys                                 
(023210) [22:01:22] % sudo du --summarize --block-size=1 /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51                             
668180480       /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51                                                                      
(023210) [22:01:22] % sudo du --summarize --block-size=1 /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/boot                        
33009664        /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/boot                                                                 
(023210) [22:01:22] % sudo du --summarize --block-size=1 /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home                        
28672   /home/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home 
(023210) [22:01:22] % sudo umount /media/data/clayton/src/pmbootstrap-out/chroot_native/dev/install                                             
[22:01:22] EVERYTHING ON /dev/sdc WILL BE ERASED! CONTINUE? (y/n) [n] y 
(023210) [22:01:23] (native) mount /dev/install (host: /dev/sdc)        
(023210) [22:01:23] % sudo mount --bind /dev/sdc /home/clayton/src/pmbootstrap-out/chroot_native/dev/install                                    
(023210) [22:01:23] (native) partition /dev/install (boot: 46M, root: the rest)                                                                 
(023210) [22:01:23] (native) % parted -s /dev/install mktable msdos     
(023210) [22:01:23] (native) % parted -s /dev/install mkpart primary ext2 2048s 46M                                                             
(023210) [22:01:23] (native) % parted -s /dev/install mkpart primary 46M 100%                                                                   
(023210) [22:01:23] (native) % parted -s /dev/install set 1 boot on     
(023210) [22:01:23] ERROR: Unable to find the partition prefix, expected the first partition of /dev/sdc to be located at /dev/sdc1 or /dev/sdcp1!
(023210) [22:01:23] Run 'pmbootstrap log' for details.                  
(023210) [22:01:23] See also: <https://postmarketos.org/troubleshooting>                                                                        
(023210) [22:01:23] Traceback (most recent call last):                  
  File "./pmbootstrap.py", line 53, in main                             
    getattr(pmb.helpers.frontend, args.action)(args)                    
  File "/media/data/clayton/src/pmbootstrap/pmb/helpers/frontend.py", line 113, in install                                                      
    pmb.install.install(args)       
  File "/media/data/clayton/src/pmbootstrap/pmb/install/install.py", line 285, in install                                                       
    install_system_image(args)      
  File "/media/data/clayton/src/pmbootstrap/pmb/install/install.py", line 165, in install_system_image                                          
    pmb.install.partition(args, size_boot)                              
  File "/media/data/clayton/src/pmbootstrap/pmb/install/partition.py", line 77, in partition                                                    
    partitions_mount(args)          
  File "/media/data/clayton/src/pmbootstrap/pmb/install/partition.py", line 43, in partitions_mount                                             
    "1 or " + prefix + "p1!")       
RuntimeError: Unable to find the partition prefix, expected the first partition of /dev/sdc to be located at /dev/sdc1 or /dev/sdcp1!           
```

```
$ ls /dev/sdc*
/dev/sdc  /dev/sdc1  /dev/sdc2
$ fdisk -l /dev/sdc
Disk /dev/sdc: 59.5 GiB, 63864569856 bytes, 124735488 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xfad073e3

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdc1  *     2048     90111     88064   43M 83 Linux
/dev/sdc2       90112 124735487 124645376 59.4G 83 Linux

**Comment by ollieparanoid** [comment]
*Follow up to #463.* Alright, I have two solutions for this.

1. Run `partprobe` after the parted commands (busybox does partprobe, so we don't need to install anything):
```patch
--- a/pmb/install/partition.py
+++ b/pmb/install/partition.py
@@ -74,4 +74,5 @@ def partition(args, size_boot):
                         command, check=False)

     # Mount new partitions
+    pmb.chroot.root(args, ["partprobe", "/dev/install"])
     partitions_mount(args)
```
2. If that does not work, we could try to find the partition in a loop with a 100ms delay after each try, and for 20 times (2 seconds) or something like that.

Could you try the first patch and tell me if it works? 👍

**Comment by craftyguy** [comment]
@ollieparanoid I really appreciate the help on this!

Unfortunately calling partprobe doesn't resolve it.. The error doesn't happen every time, but I can't characterize it to any particular sequence of events that I am doing.

**Comment by ollieparanoid** [comment]
Thanks for testing! I made a PR for the second approach I've mentioned above.
