### ISSUE TITLE
pmbootstrap shutdown confused by deleted /dev/loop3p2 node

### ISSUE THREAD

**Issue by zhuowei** [postmarketOS/pmbootstrap#545]
I received this error when running `pmbootstrap shutdown`:

```(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/mnt/install/boot
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/mnt/install
(007366) [23:02:19] (native) % losetup --json --list
{
   "loopdevices": [
      {"name": "/dev/loop0", "sizelimit": "0", "offset": "0", "autoclear": "0", "ro": "0", "back-file": "/media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/*", "dio": "0"},
      {"name": "/dev/loop1", "sizelimit": "0", "offset": "0", "autoclear": "0", "ro": "0", "back-file": "/media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/*", "dio": "0"},
      {"name": "/dev/loop2", "sizelimit": "0", "offset": "0", "autoclear": "0", "ro": "0", "back-file": "/media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/*", "dio": "0"},
      {"name": "/dev/loop3", "sizelimit": "0", "offset": "0", "autoclear": "0", "ro": "0", "back-file": "/home/user/rootfs/huawei-angler.img", "dio": "0"}
   ]
}
(007366) [23:02:19] (native) umount /dev/loop3
(007366) [23:02:19] (native) % losetup -d /dev/loop3
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/var/cache/distfiles
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/var/cache/apk
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/sys/devices
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/sys/dev
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/sys/bus/usb/devices
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/proc
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/mnt/rootfs_huawei-angler
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/packages/user
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/git
(007366) [23:02:19] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/.ccache
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/home/user/.abuild
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/etc/apk/keys
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop7
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop6
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop5
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop4
(007366) [23:02:20] % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop3p2\040(deleted)
umount: /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop3p2\040(deleted): not found
(007366) [23:02:20] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(007366) [23:02:20] NOTE: The failed command's output is above the ^^^ line in the logfile: /media/zhuowei/redhd/docs/pmbootstrap/log.txt
(007366) [23:02:20] ERROR: Command failed: % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop3p2\040(deleted)
(007366) [23:02:20] Run 'pmbootstrap log' for details.
(007366) [23:02:20] See also: <https://postmarketos.org/troubleshooting>
(007366) [23:02:20] Traceback (most recent call last):
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/run.py", line 45, in core
    stderr=args.logfd)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'umount', '/media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop3p2\\040(deleted)']' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/__init__.py", line 53, in main
    getattr(frontend, args.action)(args)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/frontend.py", line 174, in shutdown
    pmb.chroot.shutdown(args)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/chroot/shutdown.py", line 93, in shutdown
    pmb.helpers.mount.umount_all(args, args.work)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/mount.py", line 107, in umount_all
    pmb.helpers.run.root(args, ["umount", mountpoint])
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/run.py", line 85, in root
    return user(args, cmd, log, working_dir, return_stdout, check)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/run.py", line 76, in user
    return core(args, cmd, msg, log, return_stdout, check, working_dir)
  File "/media/zhuowei/redhd/docs/repos/pmbootstrap/pmb/helpers/run.py", line 58, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: % sudo umount /media/zhuowei/redhd/docs/pmbootstrap/chroot_native/dev/loop3p2\040(deleted)
```

**Comment by ollieparanoid** [comment]
Which Linux distribution do you run it on? I haven't seen deleted loop devices being listed in `/proc/mtab` yet, but that seems to be the issue here.
[`umount_all_list`](https://github.com/postmarketOS/pmbootstrap/blob/20abe8e8ca4b593d80e832a7ef08cf0b4e827936/pmb/helpers/mount.py#L82) is responsible for the list of mountpoints, that get umounted we could filter for mountpoints with `\040(deleted)` at the end, but I am not sure if this is the proper fix here.

Why did the loop device get "deleted" anyway, maybe you could figure that out?
Thanks for making this detailed bug report! 👍

**Comment by zhuowei** [comment]
@ollieparanoid Ubuntu 14.04.3. I'm not sure why: this happened when I was messing with serving the root FS via NFS.

**Comment by ollieparanoid** [comment]
(Closed until someone can reproduce it.)

**Comment by zhuowei** [comment]
I still don't have a good way to reproduce it, but it happens on my device very often. I sent a patch that fixes the symptom of this (pmbootstrap shutdown not working properly), but I don't know the root cause.
