### ISSUE TITLE
Cannot cross-compile ofono 1.21 (armhf)

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#751]
ofono fails to build from source for armhf, however I can compile it for x86_64.

Build log here:

```
(004962) [17:26:15] (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
>>> ofono: abuild 3.0.2-r0
>>> ofono: Checking sanity of /home/pmos/build/APKBUILD...
>>> WARNING: ofono: No maintainer
>>> ofono: Cleaning temporary build dirs...
>>> ofono: Fetching https://www.kernel.org/pub/linux/network/ofono/ofono-1.21.tar.xz
>>> ofono: Fetching https://www.kernel.org/pub/linux/network/ofono/ofono-1.21.tar.xz
>>> ofono: Checking sha512sums...
ofono-1.21.tar.xz: OK
ofono.initd: OK
0004-nokia-gpio-do-not-create-links-to-gpios-in-dev-cmt.patch: OK
>>> WARNING: ofono: ofono.initd is not an openrc #!/sbin/openrc-run
>>> ofono: Unpacking /var/cache/distfiles/ofono-1.21.tar.xz...
>>> ofono: 0004-nokia-gpio-do-not-create-links-to-gpios-in-dev-cmt.patch
patching file plugins/nokia-gpio.c
(005240) [17:26:16] % tail -f /var/pmbootstrap/log.txt -n 60
(005240) [17:26:16] *** output passed to pmbootstrap stdout, not to this log ***
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... configure: error: in `/home/pmos/build/src/ofono-1.21':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
>>> ERROR: ofono: all failed
(004962) [17:26:20] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(004962) [17:26:20] NOTE: The failed command's output is above the ^^^ line in the logfile: /var/pmbootstrap/log.txt
(004962) [17:26:20] ERROR: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
(004962) [17:26:20] Run 'pmbootstrap log' for details.
(004962) [17:26:20] See also: <https://postmarketos.org/troubleshooting>
(004962) [17:26:20] Traceback (most recent call last):
  File "/home/pablo2/src/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /var/pmbootstrap/chroot_buildroot_armhf sh -c \'cd /home/pmos/build;su pmos -c \'"\'"\'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d\'"\'"\'\'']' returned non-zero exit status 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pablo2/src/pmbootstrap/pmb/__init__.py", line 57, in main
    getattr(frontend, args.action)(args)
  File "/home/pablo2/src/pmbootstrap/pmb/helpers/frontend.py", line 141, in install
    pmb.install.install(args)
  File "/home/pablo2/src/pmbootstrap/pmb/install/install.py", line 302, in install
    pmb.chroot.apk.install(args, install_packages, suffix)
  File "/home/pablo2/src/pmbootstrap/pmb/chroot/apk.py", line 204, in install
    args, build, arch, package, packages_installed):
  File "/home/pablo2/src/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/home/pablo2/src/pmbootstrap/pmb/build/package.py", line 114, in package
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build")
  File "/home/pablo2/src/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/pablo2/src/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/pablo2/src/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
```

**Comment by PabloCastellano** [comment]
Closing as it looks like a permission error possibly related to #709

This fragment of log comes from `config.log`:

```
ccache: error: Failed to create directory /home/pmos/.ccache/tmp: Permission denied
distcc[17388] ERROR: compile conftest.c on localhost failed
configure:3684: $? = 1        
configure: failed program was:
| /* confdefs.h */        
| #define PACKAGE_NAME "ofono"                         
| #define PACKAGE_TARNAME "ofono"
| #define PACKAGE_VERSION "1.21"
| #define PACKAGE_STRING "ofono 1.21"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""        
| #define PACKAGE "ofono"       
| #define VERSION "1.21"                         
| /* end confdefs.h.  */                
|                                  
| int                           
| main ()                       
| {                                      
|                                          
|   ;                    
|   return 0;          
| }                    
configure:3698: error: in `/home/pmos/build/src/ofono-1.21':
configure:3701: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
```

Turns out that for some reason the `cache_ccache_*` directories only had write permission for root:

```
drwxr-xr-x  2 root   root      4096 Oct 12 13:35 cache_ccache_aarch64
drwxr-xr-x  2 root   root      4096 Oct 12 13:26 cache_ccache_armhf
drwxr-xr-x 19  12345  12345    4096 Oct 12 17:41 cache_ccache_x86_64
```

However `cache_ccache_x86_64` had uid 12345 as owner.

Chown the other directories to 12345:12345 solved the issue.
After chown
