### ISSUE TITLE
Unable to install pmOS after #725

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#754]
I followed the instructions in @PabloCastellano's commit message for #725, and get this failure when running `pmbootstrap install` right after:

```
(027194) [13:32:18] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
(027194) [13:32:18] (native) % apk --no-progress add -u qemu-user-static-repack qemu-user-static-repack-binfmt
WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
ERROR: unsatisfiable constraints:
  qemu-user-static-repack (missing):
    required by: world[qemu-user-static-repack]
  qemu-user-static-repack-binfmt (missing):
    required by:
                 world[qemu-user-static-repack-binfmt]
(027194) [13:32:21] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(027194) [13:32:21] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/clayton/src/pmbootstrap-out/log.txt
(027194) [13:32:21] ERROR: Command failed: (native) % apk --no-progress add -u qemu-user-static-repack qemu-user-static-repack-binfmt
(027194) [13:32:21] Run 'pmbootstrap log' for details.
(027194) [13:32:21] See also: <https://postmarketos.org/troubleshooting>
(027194) [13:32:21] Traceback (most recent call last):
  File "/media/data/clayton/src/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/clayton/src/pmbootstrap-out/chroot_native sh -c 'cd /;apk --no-progress add -u qemu-user-static-repack qemu-user-static-repack-binfmt'"]' returned non-zero exit status 2.


```

I also tried completely clearing out my pmbootstrap working directory, but still experience the same failure.

Interestingly enough, the package it is looking for does exist under `<pmb work dir>/pacakges/x86_64/qemu-user-static-repack-2.8-r8.apk`.

**Comment by ollieparanoid** [comment]
Sorry that I broke it for you! The instructions are outdated, I've edited the message in the PR accordingly. This is handled by the safe upgrade path, that was implemented later on.

If you don't mind losing your ccache and packages (not you KDE builders!), the easiest way to recover from that would be:
```shell
pmbootstrap shutdown
sudo rm -rf $WORKDIR
```

**Comment by craftyguy** [comment]
After chatting with @ollieparanoid on Matrix, looks like this is caused by pmbootstrap-related apk signing keys are not copied to `/etc/apk/keys/` in the native chroot, thus causing apk to ignore the local repo index:

> WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
