### ISSUE TITLE
pmbootstrap shutdown doesn't properly detect if the cryptsetup partition is opened

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#83]
I get this error on `pmbootstrap.py shutdown` and all commands that use it:

```
(015045) [21:40:00] *** (3/5) PREPARE INSTALL BLOCKDEVICE ***
(015045) [21:40:00] (native) % cryptsetup luksClose pm_crypt
Device pm_crypt is not active.
(015045) [21:40:00] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(015045) [21:40:00] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/martijn/.local/var/pmbootstrap/log.txt
(015045) [21:40:00] ERROR: Command failed: (native) % cryptsetup luksClose pm_crypt
(015045) [21:40:00] Run 'pmbootstrap log' for details.
(015045) [21:40:00] Traceback (most recent call last):
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/martijn/.local/var/pmbootstrap/chroot_native sh -c 'cd /;cryptsetup luksClose pm_crypt'"]' returned non-zero exit status 4.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 74, in main
    pmb.install.install(args)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/install/install.py", line 114, in install
    pmb.chroot.shutdown(args, True)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/shutdown.py", line 38, in shutdown
    pmb.chroot.root(args, ["cryptsetup", "luksClose", "pm_crypt"])
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 52, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cryptsetup luksClose pm_crypt
```

**Comment by ollieparanoid** [comment]
Seems like the check for the opened cryptsetup partition isn't good enough. `pmb/chroot/shutdown.py`:

```py
    if os.path.exists(args.work + "/chroot_native/dev/mapper/pm_crypt"):
        pmb.chroot.root(args, ["cryptsetup", "luksClose", "pm_crypt"])
```

Looks like you have a left over file in `~/.local/var/pmbootstrap/chroot_native/dev/mapper/pm_crypt`. Delete that file, and it should work.

I'm leaving this ticket open to implement a proper check (by directly asking cryptsetup if there's anything opened under that path).
