### ISSUE TITLE
[bullhead] Possible to port to ARM64?

### ISSUE THREAD

**Issue by hellux** [postmarketOS/pmbootstrap#84]
I'm trying to port to Nexus 5X, when attempting to compile for ARM64 the following command fails:
`su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgn`
I noticed it's using armv6 which does not support 64-bit. Does alpine support ARM64 at all? How do I obtain those builds instead with the strapper?

Full error output from log: 
```
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
make[2]: *** [/home/user/build/src/android_kernel_lge_bullhead-12019f5d0fc9978f219516d494e8fa20b9a22ffb/Makefile:522: scripts] Error 2
make[1]: *** [Makefile:130: sub-make] Error 2
make: *** [Makefile:26: all] Error 2
>>> ERROR: linux-lg-bullhead: all failed
(027435) [21:12:49] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(027435) [21:12:49] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/noah/.local/var/pmbootstrap/log.txt
(027435) [21:12:49] ERROR: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d'
(027435) [21:12:49] Run 'pmbootstrap log' for details.
(027435) [21:12:49] Traceback (most recent call last):
  File "/home/noah/src/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/noah/.local/var/pmbootstrap/chroot_native sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 60, in main
    args.buildinfo)
  File "/home/noah/src/pmbootstrap/pmb/build/package.py", line 107, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/home/noah/src/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/noah/src/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/home/noah/src/pmbootstrap/pmb/helpers/run.py", line 52, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /home/user/build && su user -c 'CARCH=armhf CROSS_COMPILE=armv6-alpine-linux-muslgnueabihf- CC=armv6-alpine-linux-muslgnueabihf-gcc abuild -d'
```

**Comment by MartijnBraam** [comment]
For arm64 you need to change the `arch="armhf"` to `arch="aarch64"` and `_carch="arm"` to `_carg="arm64"` in your apkbuild.

Also your error output doesn't contain the actual error. you need to scroll up in the kernel compile log until you find more make errors and you'll find the code error.

**Comment by hellux** [comment]
I didn't realize I had to change the arch variable as well. That solved the problem, thank you!

I see, I misread those for warnings, thanks.

**Comment by ollieparanoid** [comment]
You will need some additional packages to get aarch64 working, but you can generate all of them:
```
pmbootstrap aportgen binutils-aarch64
pmbootstrap aportgen musl-aarch64
pmbootstrap aportgen gcc-aarch64
```
`pmb/parse/arch.py` might also need to get adjusted a bit (translating `aarch64` to Debian's architecture for the qemu user mode emulation etc.).

Other than that it *should* just work like `armhf`.

I'll include "officiall" aarch64 support soon (feel free to beat me to it with a PR).
