### ISSUE TITLE
Building weston for aarch64 fails

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#87]
I've just tried to make an image for aarch64 but the install fails at compiling weston

```
**mtdev-dev-1.1.5-r1 - Multitouch Protocol Translation Library Development Package (development files)
libxft-2.3.2-r1 - FreeType-based font drawing library for X
graphite2-1.3.10-r0 - reimplementation of the SIL Graphite text processing engine
harfbuzz-1.4.6-r0 - Text shaping library
pango-1.40.5-r0 - A library for layout and rendering of text
icu-libs-58.2-r2 - International Components for Unicode library (libraries)
harfbuzz-icu-1.4.6-r0 - Harfbuzz ICU support library
graphite2-dev-1.3.10-r0 - reimplementation of the SIL Graphite text processing engine (development files)
icu-dev-58.2-r2 - International Components for Unicode library (development files)
harfbuzz-dev-1.4.6-r0 - Text shaping library (development files)
libxft-dev-2.3.2-r1 - FreeType-based font drawing library for X (development files)
pango-dev-1.40.5-r0 - A library for layout and rendering of text (development files)
wayland-protocols-1.7-r3 - Protocols and protocol extensions complementing the Wayland core protocol
xkeyboard-config-2.21-r0 - X keyboard configuration files
popt-1.16-r6 - A commandline option parser
distcc-3.1-r12 - A distributed C, C++, Obj C compiler
(008007) [22:53:08] (buildroot_aarch64) build aarch64/weston-9999-r0.apk
(008007) [22:53:08] (buildroot_aarch64) % rm -rf /home/user/build
(008007) [22:53:08] % sudo cp -r /home/martijn/Projects/Other/pmbootstrap/aports/weston/ /home/martijn/.local/var/pmbootstrap/chroot_buildroot_aarch64/home/user/build
(008007) [22:53:08] (buildroot_aarch64) % chown -R user:user /home/user/build
(008007) [22:53:08] (buildroot_aarch64) % cd /home/user/build && su user -c 'CARCH=aarch64 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
>>> ERROR: weston: all failed
(008007) [22:53:08] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(008007) [22:53:08] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/martijn/.local/var/pmbootstrap/log.txt
(008007) [22:53:08] ERROR: Command failed: (buildroot_aarch64) % cd /home/user/build && su user -c 'CARCH=aarch64 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
(008007) [22:53:08] Run 'pmbootstrap log' for details.
(008007) [22:53:08] Traceback (most recent call last):
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 39, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'unset $(env | cut -d= -f1); CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/martijn/.local/var/pmbootstrap/chroot_buildroot_aarch64 sh -c \'cd /home/user/build;su user -c \'"\'"\'CARCH=aarch64 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pmbootstrap.py", line 74, in main
    pmb.install.install(args)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/install/install.py", line 100, in install
    pmb.build.package(args, pkgname, args.deviceinfo["arch"])
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/build/package.py", line 59, in package
    package(args, depend, carch)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/build/package.py", line 107, in package
    pmb.chroot.user(args, cmd, suffix, "/home/user/build")
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/chroot/root.py", line 85, in root
    return_stdout, check)
  File "/home/martijn/Projects/Other/pmbootstrap/pmb/helpers/run.py", line 52, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_aarch64) % cd /home/user/build && su user -c 'CARCH=aarch64 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
**
```

My current branch: https://github.com/MartijnBraam/pmbootstrap/tree/device-raspi3

**Comment by ollieparanoid** [comment]
* Does it work, when running `pmbootstrap shutdown` before? (guessing, that it might relate to binfmt stuff)
* Could you manually enter the chroot with `pmbootstrap chroot --suffix=buildroot_aarch64` and run the commands manually?
```
su - user
cd /home/user/build
CARCH=aarch64 PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d
```
* If that does not work: `abuild` is a shell script. Edit it as root user and add `set -x` at the beginning, so it shows every command. then we should see, where it is failing.

**Comment by MartijnBraam** [comment]
Shutdown doesn't help

hello-wold compiles fine

This is the set -x output:

```
+ program_version=3.0.0_rc2
+ sysconfdir=/etc
+ datadir=/usr/share/abuild
+ readlink -f /usr/bin/abuild
+ abuild_path=/usr/bin/abuild
+ [ -f /usr/share/abuild/functions.sh ]
+ . /usr/share/abuild/functions.sh
+ sysconfdir=/etc
+ program=abuild
+ readconfig
+ local _APORTSDIR _BUILDDIR _PKGDEST _SRCPKGDEST _REPODEST _SRCDEST
+ local _CARCH _CHOST _CTARGET _CPPFLAGS _CFLAGS _CXXFLAGS _LDFLAGS
+ local _JOBS _MAKEFLAGS _PACKAGER _USE_COLORS
+ local gitbase=
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n x ]
+ _CARCH=aarch64
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ [ -n  ]
+ : /etc/abuild.conf
+ : /home/user/.abuild
+ : /home/user/.abuild/abuild.conf
+ [ -f /etc/abuild.conf ]
+ . /etc/abuild.conf
+ export CFLAGS=-Os -fomit-frame-pointer
+ export CXXFLAGS=-Os -fomit-frame-pointer
+ export CPPFLAGS=-Os -fomit-frame-pointer
+ export LDFLAGS=-Wl,--as-needed
+ export JOBS=5
+ export MAKEFLAGS=-j5
+ USE_COLORS=1
+ SRCDEST=/var/cache/distfiles
+ REPODEST=/home/user/packages/
+ CLEANUP=
+ ERROR_CLEANUP=deps
+ [ -f /home/user/.abuild/abuild.conf ]
+ . /home/user/.abuild/abuild.conf
+ PACKAGER_PRIVKEY=/home/user/.abuild/user-592e901f.rsa
+ APORTSDIR=
+ git rev-parse --show-toplevel
+ gitbase=
+ true
+ [ -d  ]
+ [ -z  ]
+ [ -d /home/user/aports ]
+ [ -n  ]
+ APORTSDIR=
+ [ -n  ]
+ BUILDDIR=
+ PKGDEST=
+ SRCPKGDEST=
+ REPODEST=/home/user/packages/
+ SRCDEST=/var/cache/distfiles
+ CARCH=aarch64
+ CHOST=
+ CTARGET=
+ CPPFLAGS=-Os -fomit-frame-pointer
+ CFLAGS=-Os -fomit-frame-pointer
+ CXXFLAGS=-Os -fomit-frame-pointer
+ LDFLAGS=-Wl,--as-needed
+ JOBS=5
+ MAKEFLAGS=-j5
+ PACKAGER=
+ USE_COLORS=1
+ [ -z  ]
+ gcc -dumpmachine
+ CBUILD=aarch64-alpine-linux-musl
+ [ -z  ]
+ CHOST=aarch64-alpine-linux-musl
+ [ -z  ]
+ CTARGET=aarch64-alpine-linux-musl
+ arch_to_hostspec aarch64-alpine-linux-musl
+ echo unknown
+ [ unknown != unknown ]
+ arch_to_hostspec aarch64-alpine-linux-musl
+ echo unknown
+ [ unknown != unknown ]
+ arch_to_hostspec aarch64-alpine-linux-musl
+ echo unknown
+ [ unknown != unknown ]
+ [ -z aarch64 ]
+ [ -z  ]
+ hostspec_to_libc aarch64-alpine-linux-musl
+ echo musl
+ CLIBC=musl
+ [ -z  ]
+ hostspec_to_arch aarch64-alpine-linux-musl
+ echo aarch64
+ CBUILD_ARCH=aarch64
+ [ -z  ]
+ hostspec_to_arch aarch64-alpine-linux-musl
+ echo aarch64
+ CTARGET_ARCH=aarch64
+ [ -z  ]
+ hostspec_to_libc aarch64-alpine-linux-musl
+ echo musl
+ CTARGET_LIBC=musl
+ [ aarch64-alpine-linux-musl != aarch64-alpine-linux-musl ]
+ [ aarch64-alpine-linux-musl != aarch64-alpine-linux-musl ]
+ [ -n 1 ]
+ [ -t 1 ]
+ enable_colors
+ NORMAL=\033[1;0m
+ STRONG=\033[1;1m
+ RED=\033[1;31m
+ GREEN=\033[1;32m
+ YELLOW=\033[1;33m
+ BLUE=\033[1;34m
+ : fakeroot
+ : abuild-apk
+ : apk
+ : abuild-adduser
+ : abuild-addgroup
+ apk_opt_wait=--wait 30
+ umask 022
+ APKBUILD=./APKBUILD
+ unset force
+ unset recursive
+ getopts AcdfFhkKimnp:P:qrRs:u opt
+ nodeps=-d
+ getopts AcdfFhkKimnp:P:qrRs:u opt
+ shift 1
+ id -u
+ [ 12345 -eq 0 ]
+ [ -f ./APKBUILD ]
+ readlink -f ./APKBUILD
+ APKBUILD=/home/user/build/APKBUILD
+ startdir=/home/user/build
+ srcdir=/home/user/build/src
+ pkgbasedir=/home/user/build/pkg
+ repo=/home/user
+ repo=user
+ SRCDEST=/var/cache/distfiles
+ : gcc
+ export CC
+ cd /home/user/build
+ . /home/user/build/APKBUILD
+ pkgname=weston
+ pkgver=9999
+ _pkgver=2.0.0
+ pkgrel=0
+ _libname=libweston
+ _libdir=libweston-2
+ pkgdesc=The reference Wayland server
+ url=http://wayland.freedesktop.org
+ arch=x86_64 armhf
+ license=MIT
+ depends=
+ makedepends=wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev
+ _cms=cms-colord cms-static
+ _shell=shell-desktop shell-fullscreen shell-ivi
+ _client=info terminal wcap-decode
+ _backend=backend-drm backend-fbdev backend-headless
	backend-rdp backend-x11 backend-wayland
	
+ options=!check
+ subpackages= weston-cms-colord:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub weston-backend-rdp:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub weston-backend-rdp:_sub weston-backend-x11:_sub
+ subpackages= weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub weston-backend-rdp:_sub weston-backend-x11:_sub weston-backend-wayland:_sub
+ subpackages=weston-dev weston-doc  weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub weston-backend-rdp:_sub weston-backend-x11:_sub weston-backend-wayland:_sub
	weston-clients libweston-desktop:_libd libweston:libs
	weston-xwayland weston-desktop-x11:_x11:noarch
	
+ source=http://wayland.freedesktop.org/releases/weston-2.0.0.tar.xz no_0hz_refresh_rate.patch
+ builddir=/home/user/build/src/weston-2.0.0
+ sha512sums=085a0ba278932d41b50edd6e89db5df31cd6a1179c6cfe9a8ac5ac64e63b25cfc3da1ad8c587259273c3812593029b803867195e2d82b12b5cdd2588ac59acc6  weston-2.0.0.tar.xz
68d8485eed6a536924a8ebef7e0b45738330c38326fe659443c26d674f9538ec1c66033f83a7971914dcd72bc52333e3f55486c5a01e067e3f5fee8f5b489728  no_0hz_refresh_rate.patch
+ builddir=/home/user/build/src/weston-2.0.0
+ [ -z /home/user/packages/ ]
+ export REPODEST SRCDEST
+ [ -n  ]
+ subpackage_types_has dbg
+ local i
+ local _name=weston-dev
+ [ dbg = dev ]
+ local _name=weston-doc
+ [ dbg = doc ]
+ local _name=weston-cms-colord
+ [ dbg = colord ]
+ local _name=weston-cms-static
+ [ dbg = static ]
+ local _name=weston-shell-desktop
+ [ dbg = desktop ]
+ local _name=weston-shell-fullscreen
+ [ dbg = fullscreen ]
+ local _name=weston-shell-ivi
+ [ dbg = ivi ]
+ local _name=weston-info
+ [ dbg = info ]
+ local _name=weston-terminal
+ [ dbg = terminal ]
+ local _name=weston-wcap-decode
+ [ dbg = decode ]
+ local _name=weston-backend-drm
+ [ dbg = drm ]
+ local _name=weston-backend-fbdev
+ [ dbg = fbdev ]
+ local _name=weston-backend-headless
+ [ dbg = headless ]
+ local _name=weston-backend-rdp
+ [ dbg = rdp ]
+ local _name=weston-backend-x11
+ [ dbg = x11 ]
+ local _name=weston-backend-wayland
+ [ dbg = wayland ]
+ local _name=weston-clients
+ [ dbg = clients ]
+ local _name=libweston-desktop
+ [ dbg = desktop ]
+ local _name=libweston
+ [ dbg = libweston ]
+ local _name=weston-xwayland
+ [ dbg = xwayland ]
+ local _name=weston-desktop-x11
+ [ dbg = x11 ]
+ return 1
+ [ -n  ]
+ allpackages=weston weston-dev weston-doc  weston-cms-colord:_sub weston-cms-static:_sub weston-shell-desktop:_sub weston-shell-fullscreen:_sub weston-shell-ivi:_sub weston-info:_sub weston-terminal:_sub weston-wcap-decode:_sub weston-backend-drm:_sub weston-backend-fbdev:_sub weston-backend-headless:_sub weston-backend-rdp:_sub weston-backend-x11:_sub weston-backend-wayland:_sub
	weston-clients libweston-desktop:_libd libweston:libs
	weston-xwayland weston-desktop-x11:_x11:noarch
	
+ apkbuild_arch=x86_64 armhf
+ pkgdir=/home/user/build/pkg/weston
+ [ -z  ]
+ pkgarch=aarch64
+ list_has noarch x86_64 armhf
+ local needle=noarch
+ local i
+ shift
+ [ noarch = x86_64 ]
+ [ noarch = !x86_64 ]
+ [ noarch = armhf ]
+ [ noarch = !armhf ]
+ return 1
+ controldir=/home/user/build/pkg/.control.weston
+ trap die "Aborted by user" INT
+ [ -z  ]
+ set_xterm_title abuild: weston
+ [  = xterm ]
+ [ -z  ]
+ set all
+ [ 1 -gt 0 ]
+ runpart all
+ local part=all
+ [ -n  ]
+ trap die 'all failed' EXIT
+ all
+ [ -n  ]
+ check_arch
+ local ret=1
+ local i
+ return 1
+ die all failed
+ error all failed
+ local prompt=\033[1;31m>>> ERROR:\033[1;0m
+ local fake=
+ local name=\033[1;1mweston\033[1;0m
+ printf \033[1;31m>>> ERROR:\033[1;0m \033[1;1mweston\033[1;0m: %s\n all failed
>>> ERROR: weston: all failed
+ logcmd ERROR: weston: all failed
+ true ERROR: weston: all failed
+ return 0
+ cleanup deps
+ local i=
+ [ -z  ]
+ set_xterm_title 
+ [  = xterm ]
+ [ -n  ]
+ [ -z  ]
+ [ -n  ]
+ exit
```

**Comment by ollieparanoid** [comment]
Yeah, it's really hard to read, but I found the issue:
https://github.com/postmarketOS/pmbootstrap/blob/master/aports/weston/APKBUILD#L13
I guess it works, when you add `aarch64` there :)

I'll add a new ticket to output a better error message (from pmbootstrap) for this situation.
