### ISSUE TITLE
install dies with unable to find so:libcrypto.so.41

### ISSUE THREAD

**Issue by lws-team** [postmarketOS/pmbootstrap#895]
```
[14:09:48] *** (1/5) PREPARE NATIVE CHROOT ***
[14:09:48] (native) install alpine-base
[14:09:59] (native) install cryptsetup util-linux e2fsprogs parted
[14:10:09] *** (2/5) CREATE DEVICE ROOTFS ("htc-bravo") ***
[14:10:09] (native) install abuild build-base ccache
[14:10:30] (native) generate abuild keys
[14:10:30] (native) install xz
[14:10:33] (native) build x86_64/qemu-user-static-repack-2.8-r9.apk
[14:10:42] (native) install qemu-user-static-repack qemu-user-static-repack-binfmt
[14:10:43] Register qemu binfmt (arm)
[14:10:43] (rootfs_htc-bravo) install alpine-base
[14:10:59] (native) build x86_64/postmarketos-base-3-r11.apk
[14:11:00] (native) build x86_64/device-htc-bravo-1-r8.apk
[14:11:01] (native) build x86_64/postmarketos-ui-weston-4-r3.apk
[14:11:01] (native) build x86_64/postmarketos-mkinitfs-0.5.3-r0.apk
[14:11:02] (native) install perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev
[14:11:11] (native) build x86_64/musl-armhf-1.1.18-r0.apk
[14:11:17] (native) install gettext libtool autoconf automake bison
[14:11:25] (native) build x86_64/binutils-armhf-2.28-r3.apk
[14:13:29] (native) install paxmark bison flex texinfo gawk zip mpfr-dev mpc1-dev zlib-dev mpfr-dev mpc1-dev isl-dev zlib-dev musl-dev-armhf binutils-armhf
[14:13:36] (native) build x86_64/gcc-armhf-6.4.0-r5.apk
[14:19:25] (native) build x86_64/ccache-cross-symlinks-1-r3.apk
[14:19:27] (native) install gcc-armhf g++-armhf ccache-cross-symlinks
[14:19:28] (native) build armhf/linux-htc-bravo-3.0.16-r8.apk
[14:22:05] (native) build x86_64/mkbootimg-14.1-r1.apk
[14:22:07] (buildroot_armhf) install alpine-base
[14:22:13] (buildroot_armhf) install abuild build-base ccache
[14:22:37] ERROR: Could not find package 'so:libcrypto.so.41' in the aports folder and could not find it in any APKINDEX
```

**Comment by ollieparanoid** [comment]
Welcome @lws-team and thanks for reporting!

Unfortunately, `libressl` (which provides `libcrypto.so`) just had an [`soname`](https://en.wikipedia.org/wiki/Soname) bump in Alpine Linux yesterday. This means, that all packages, that link against it, need to be rebuilt.

The `armhf` packages for `freerdp-libs` for `armhf` have not been rebuilt yet (the new version is `2.0.0_rc0-r1`), as you can see [here](https://pkgs.alpinelinux.org/packages?name=freerdp-libs&branch=edge&repo=&arch=&maintainer=).

I'm working on a patch for our `weston` package, so it builds without `freerdp-libs` (which is for remote desktop, a feature that we don't use right now anyway). In the meantime, you could try another UI than weston, e.g. `none` (select it in `pmbootstrap init`).

**Comment by lws-team** [comment]
Thanks.  Yeah the patch lets it get past that.

Doesn't alpine have packages for these things?  Then you could just compose the image from the current binary packages?

**Comment by lws-team** [comment]
It dies shortly afterwards with this

```
>>> weston-backend-headless*: Stripping binaries
/usr/bin/abuild: line 2534: git: not found
/usr/bin/abuild: line 2534: git: not found
>>> weston-backend-headless*: Running postcheck for weston-backend-headless
>>> weston-backend-rdp*: Running split function _sub...
grep: /home/pmos/build/pkg/weston//usr/lib/libweston-3/rdp-backend.so: No such file or directory
mv: can't rename '/home/pmos/build/pkg/weston//usr/lib/libweston-3/rdp-backend.so': No such file or directory
>>> ERROR: weston-backend-rdp*: _sub failed
>>> ERROR: weston*: prepare_subpackages failed
>>> ERROR: weston: all failed
(002572) [19:43:46] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(002572) [19:43:46] NOTE: The failed command's output is above the ^^^ line in the logfile: /projects/postmarketos/work/log.txt
(002572) [19:43:46] ERROR: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
(002572) [19:43:46] Run 'pmbootstrap log' for details.
(002572) [19:43:46] See also: <https://postmarketos.org/troubleshooting>
(002572) [19:43:46] Traceback (most recent call last):
  File "/projects/postmarketos/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /projects/postmarketos/work/chroot_buildroot_armhf sh -c \'cd /home/pmos/build;su pmos -c \'"\'"\'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/postmarketos/pmbootstrap/pmb/__init__.py", line 58, in main
    getattr(frontend, args.action)(args)
  File "/projects/postmarketos/pmbootstrap/pmb/helpers/frontend.py", line 145, in install
    pmb.install.install(args)
  File "/projects/postmarketos/pmbootstrap/pmb/install/install.py", line 312, in install
    pmb.chroot.apk.install(args, install_packages, suffix)
  File "/projects/postmarketos/pmbootstrap/pmb/chroot/apk.py", line 204, in install
    args, build, arch, package, packages_installed):
  File "/projects/postmarketos/pmbootstrap/pmb/chroot/apk.py", line 120, in install_is_necessary
    pmb.build.package(args, package, arch)
  File "/projects/postmarketos/pmbootstrap/pmb/build/package.py", line 114, in package
    pmb.chroot.user(args, cmd, suffix, "/home/pmos/build")
  File "/projects/postmarketos/pmbootstrap/pmb/chroot/user.py", line 32, in user
    auto_init, return_stdout, check)
  File "/projects/postmarketos/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/projects/postmarketos/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (buildroot_armhf) % cd /home/pmos/build && su pmos -c 'CARCH=armhf PATH=/usr/lib/distcc/bin:/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
```

There really is no such `/home/pmos` as in

`mv: can't rename '/home/pmos/build/pkg/weston//usr/lib/libweston-3/rdp-backend.so': No such file or directory`

**Comment by ollieparanoid** [comment]
postmarketOS is a thin layer on top of Alpine. We use their binary packages whenever possible. It is not possible for `weston` yet, because we use a patch for some Android devices, to resolve a "red screen bug". And that patch is not upstreamed yet.

The breakage with the `freerdp-libs` is in the upstream repositories from Alpine. However we are using the `testing` repository right now, so when postmarketOS becomes closer to being a daily driver, we would switch to their stable repositories and shouldn't have such breakage anymore.

**Comment by ollieparanoid** [comment]
Sorry, the patch was incomplete. Here's the correct one and building it has just passed on my test machine:
```diff
--- a/aports/main/weston/APKBUILD
+++ b/aports/main/weston/APKBUILD
@@ -15,12 +15,12 @@ url="http://wayland.freedesktop.org"
 arch="all"
 license="MIT"
 depends=""
-makedepends="wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev freerdp-dev libwebp-dev libva-dev dbus-dev linux-pam-dev"
+makedepends="wayland-protocols libxkbcommon-dev xkeyboard-config libinput-dev libunwind-dev mtdev-dev libxcursor-dev glu-dev pango-dev colord-dev libwebp-dev libva-dev dbus-dev linux-pam-dev"
 _cms="cms-colord cms-static"
 _shell="shell-desktop shell-fullscreen shell-ivi"
 _client="info terminal wcap-decode"
 _backend="backend-drm backend-fbdev backend-headless
-       backend-rdp backend-x11 backend-wayland
+       backend-x11 backend-wayland
        "
 options="!check suid"

@@ -52,7 +52,6 @@ build() {
                --mandir=/usr/share/man \
                --localstatedir=/var \
                --libexecdir=/usr/lib/$pkgname \
-               --enable-rdp-compositor \
                --enable-screen-sharing \
                --enable-vaapi-recorder \
                --enable-clients \
```

**Comment by lws-team** [comment]
Thanks that has moved it off building weston.

**Comment by lws-team** [comment]
It dies here

```
(019620) [20:10:16] (native) create htc-bravo.img (282M)
(019620) [20:10:16] (native) % su pmos -c 'mkdir -p /home/pmos/rootfs'
(019620) [20:10:16] (native) % truncate -s 282M /home/pmos/rootfs/htc-bravo.img
(019620) [20:10:16] (native) mount /dev/install (htc-bravo.img)
(019620) [20:10:16] (native) mount /home/pmos/rootfs/htc-bravo.img (loop)
(019620) [20:10:16] % sudo modprobe loop
(019620) [20:10:16] % sudo touch /projects/postmarketos/work/chroot_native//dev/loop-control
(019620) [20:10:16] % sudo mount --bind /dev/loop-control /projects/postmarketos/work/chroot_native//dev/loop-control
(019620) [20:10:16] (native) % losetup -f /home/pmos/rootfs/htc-bravo.img
losetup: /home/pmos/rootfs/htc-bravo.img: failed to set up loop device: No such file or directory
(019620) [20:10:17] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(019620) [20:10:17] NOTE: The failed command's output is above the ^^^ line in the logfile: /projects/postmarketos/work/log.txt
(019620) [20:10:17] ERROR: Command failed: (native) % losetup -f /home/pmos/rootfs/htc-bravo.img
(019620) [20:10:17] Run 'pmbootstrap log' for details.
(019620) [20:10:17] See also: <https://postmarketos.org/troubleshooting>
(019620) [20:10:17] Traceback (most recent call last):
  File "/projects/postmarketos/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/sbin/chroot /projects/postmarketos/work/chroot_native sh -c 'cd /;losetup -f /home/pmos/rootfs/htc-bravo.img'"]' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/postmarketos/pmbootstrap/pmb/__init__.py", line 58, in main
    getattr(frontend, args.action)(args)
  File "/projects/postmarketos/pmbootstrap/pmb/helpers/frontend.py", line 145, in install
    pmb.install.install(args)
  File "/projects/postmarketos/pmbootstrap/pmb/install/install.py", line 329, in install
    install_system_image(args)
  File "/projects/postmarketos/pmbootstrap/pmb/install/install.py", line 193, in install_system_image
    pmb.install.blockdevice.create(args, size_image)
  File "/projects/postmarketos/pmbootstrap/pmb/install/blockdevice.py", line 125, in create
    create_and_mount_image(args, size)
  File "/projects/postmarketos/pmbootstrap/pmb/install/blockdevice.py", line 108, in create_and_mount_image
    pmb.install.losetup.mount(args, img_path)
  File "/projects/postmarketos/pmbootstrap/pmb/install/losetup.py", line 44, in mount
    pmb.chroot.root(args, ["losetup", "-f", img_path])
  File "/projects/postmarketos/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
                                                                                                                                               19628,3       99%
```

There's no obvious error I can see before that.

**Comment by lws-team** [comment]
The .img file exists but the perms are a bit strange... if 12345 is pmos in the chroot maybe it's normal

```
$ ls -l ../work/chroot_native/home/pmos/rootfs/htc-bravo.img
-rw-r--r--. 1 root 12345 295698432 Nov 11 20:10 ../work/chroot_native/home/pmos/rootfs/htc-bravo.img
```

Is the problem maybe about loopback device perms?

```
$ ls -l /dev/loop0
brw-rw----. 1 root disk 7, 0 Nov 11 20:10 /dev/loop0
```

I assume pmos isn't in disk group

**Comment by ollieparanoid** [comment]
Is your `loop` module loaded? (`lsmod | grep loop`)
It could be, that you just upgraded your host system's kernel, but you are still running the old kernel, and the modules (e.g. for `loop`) don't exist anymore on your disk. In that case, a reboot would help.

**Comment by ollieparanoid** [comment]
If you're still having problems with mounting the image, please open a new issue and/or join the [chat](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) (I'll hang out later there).

**Comment by lws-team** [comment]
Thanks for the help.  Loop is in there.

```
$ lsmod  | grep loop
 loop                   28672  0
```

I'll study it again later an open another issue if needed.
