### ISSUE TITLE
'No space left on device' error during pmbootstrap.py install

### ISSUE THREAD

**Issue by sagev9000** [postmarketOS/pmbootstrap#928]
Trying to build for i9100 fails when it gets to Fill Install Blockdevice

[21:26:43] ERROR: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a efs boot sys srv run root media sbin bin usr lib dev tmp etc mnt var proc /mnt/install/

cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device

**Comment by ollieparanoid** [comment]
Thanks for trying out postmarketOS! Could you post a big chunk of the end of the log file (as shown in `pmbootstrap log`)?

BTW: The i9100 currently only supports installation to a sd card (`pmbootstrap install --sdcard`).

**Comment by sagev9000** [comment]
I got the impression that I could at least get it on the internal memory if it had no user interface on it, but I guess I misunderstood. Either way:

./pmbootstrap.py install          
[19:02:06] *** (1/5) PREPARE NATIVE CHROOT ***
[19:02:06] *** (2/5) CREATE DEVICE ROOTFS ("samsung-i9100") ***
[sudo] password for sage: 
[19:02:14] (rootfs_samsung-i9100) write /etc/os-release
[19:02:14] (rootfs_samsung-i9100) mkinitfs samsung-i9100
[19:02:18]  *** SET LOGIN PASSWORD FOR: 'sage' ***
New password: 
Retype new password: 
passwd: password updated successfully
[19:03:02] NOTE: No valid keymap specified for device
[19:03:04] *** (3/5) PREPARE INSTALL BLOCKDEVICE ***
[19:03:05] DEBUG: Size of chroot: 143892929
[19:03:05] DEBUG: Full image size: 172661684.4
[19:03:05] (native) create samsung-i9100.img (165M)
[19:03:05] (native) mount /dev/install (samsung-i9100.img)
[19:03:06] (native) partition /dev/install (boot: 27M, root: the rest)
[19:03:06] WARNING: Full disk encryption is enabled!
[19:03:06] Make sure that osk-sdl has been properly configured for your device
[19:03:06] or else you will be unable to unlock the rootfs on boot!
[19:03:06] If you started a device port, it is recommended you disable
[19:03:06] FDE by re-running the install command with '--no-fde' until
[19:03:06] you have properly configured osk-sdl. More information:
[19:03:06] <https://postmarketos.org/osk-port>
[19:03:06] (native) format /dev/installp2 (root, luks), mount to /dev/mapper/pm_crypt
[19:03:06]  *** TYPE IN THE FULL DISK ENCRYPTION PASSWORD (TWICE!) ***
Enter passphrase: 
Enter passphrase for /dev/installp2: 
[19:03:12] (native) format /dev/mapper/pm_crypt (ext4), mount to /mnt/install
[19:03:13] (native) format /dev/installp1 (boot, ext2), mount to /mnt/install/boot
[19:03:13] *** (4/5) FILL INSTALL BLOCKDEVICE ***
[19:03:13] (native) copy rootfs_samsung-i9100 to /mnt/install/
[19:03:30] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/sage/.local/var/pmbootstrap/log.txt
[19:03:30] ERROR: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a boot run usr sbin srv media bin sys proc var tmp etc lib efs root dev mnt /mnt/install/
[19:03:30] Run 'pmbootstrap log' for details.
[19:03:30] See also: <https://postmarketos.org/troubleshooting>
sage@sage-laptop:~/git/pmbootstrap% ./pmbootstrap.py log
(007539) [19:03:13] (native) format /dev/installp1 (boot, ext2), mount to /mnt/install/boot
(007539) [19:03:13] (native) % mkfs.ext2 -F -q -L pmOS_boot /dev/installp1
(007539) [19:03:13] (native) % mkdir -p /mnt/install/boot
(007539) [19:03:13] (native) % mount /dev/installp1 /mnt/install/boot
(007539) [19:03:13] *** (4/5) FILL INSTALL BLOCKDEVICE ***
(007539) [19:03:13] (native) copy rootfs_samsung-i9100 to /mnt/install/
(007539) [19:03:13] (native) % cd /mnt/rootfs_samsung-i9100 && cp -a boot run usr sbin srv media bin sys proc var tmp etc lib efs root dev mnt /mnt/install/
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: can't create directory '/mnt/install/lib/device-mapper': No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: can't create directory '/mnt/install/lib/mdev': No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: can't create directory '/mnt/install/lib/security': No space left on device
cp: can't create directory '/mnt/install/efs': No space left on device
cp: can't create directory '/mnt/install/root': No space left on device
cp: can't create directory '/mnt/install/dev': No space left on device
cp: can't create directory '/mnt/install/mnt': No space left on device
(007539) [19:03:30] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(007539) [19:03:30] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/sage/.local/var/pmbootstrap/log.txt
(007539) [19:03:30] ERROR: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a boot run usr sbin srv media bin sys proc var tmp etc lib efs root dev mnt /mnt/install/
(007539) [19:03:30] Run 'pmbootstrap log' for details.
(007539) [19:03:30] See also: <https://postmarketos.org/troubleshooting>
(007539) [19:03:30] Traceback (most recent call last):
  File "/home/sage/git/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', "env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/sage/.local/var/pmbootstrap/chroot_native sh -c 'cd /mnt/rootfs_samsung-i9100;cp -a boot run usr sbin srv media bin sys proc var tmp etc lib efs root dev mnt /mnt/install/'"]' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sage/git/pmbootstrap/pmb/__init__.py", line 59, in main
    getattr(frontend, args.action)(args)
  File "/home/sage/git/pmbootstrap/pmb/helpers/frontend.py", line 148, in install
    pmb.install.install(args)
  File "/home/sage/git/pmbootstrap/pmb/install/install.py", line 331, in install
    install_system_image(args)
  File "/home/sage/git/pmbootstrap/pmb/install/install.py", line 209, in install_system_image
    copy_files_from_chroot(args)
  File "/home/sage/git/pmbootstrap/pmb/install/install.py", line 92, in copy_files_from_chroot
    working_dir=mountpoint)
  File "/home/sage/git/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/sage/git/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % cd /mnt/rootfs_samsung-i9100 && cp -a boot run usr sbin srv media bin sys proc var tmp etc lib efs root dev mnt /mnt/install/

**Comment by sagev9000** [comment]
Yep, that's me. I got the impression from the wiki that I could get away with just using the internal memory if I didn't include a UI in the install, but maybe I was mistaken. Either way, those are the errors I was gettings.

**Comment by ollieparanoid** [comment]
Oh, then please edit the wiki to reflect that it is not possible right now.

There's a plan to make flashing to system work though, but it will take some time until we have this: https://github.com/postmarketOS/pmbootstrap/issues/456#issuecomment-343686341 (you could also work on it if you are interested).

**Comment by ollieparanoid** [comment]
Thanks for editing the wiki @sagev9000! I've gotten a bit confused as I did not realize that you were trying the `netcat` method, which is described in the wiki. I assumed you were doing the regular installation.

### Flashing methods
So let me clarify:
* The regular installation with `pmbootstrap install` and `pmbootstrap flasher flash_system` is not working (the system flashing part doesn't work yet)
* However, the `netcat` installation *should* work
* Recovery installation method and sdcard installation method should work, too.

I have edited the wiki page to reflect this, and also linked to this issue regarding the "no space left" issue. Meanwhile, @montvid ran in the same issue.

### Why do you get "no space left on device"?
First some more explanation, what is going on here: During `pmbootstrap install`, we create the `rootfs_samsung-i9100` chroot, which will hold the same data, that will end up in the image file we create. That image file can be flashed via netcat, recovery install (and usually with `pmbootstrap flasher`, but not for the i9100 yet as mentioned above).

We need to set the size of that image in advance, before we copy all files into it. And it seems that at least for you two, the algorithm that calculates the image size isn't working. Therefore you get the "no space left on device" message, and with device, it means the image file we created beforehand.

**Note:** By using the `sdcard` method, you won't run into a "no space left on device" issue, because we don't create a fixed size image, but use the whole sd card size instead.

### What can we do?
The problem is, that calculating the right size of a folder isn't that trivial (see https://github.com/postmarketOS/pmbootstrap/pull/760#issuecomment-337043300).

The following snippet is where we calculate the image size, currently `120%` (`1.20`) of what we calculated the root size to be. **Could you play with this value, until it works for you** (try `1.5` etc.), and report back?

https://github.com/postmarketOS/pmbootstrap/blob/bc2784ece7dbbb5b9fbc8e1855566d3e9e770e59/pmb/install/install.py#L62-L66

(CC: @drebrez)

**Comment by ollieparanoid** [comment]
I can reproduce this now (selected `plasma-mobile` as UI, maybe that triggers it?).
Made a PR with a fix, that works for me (always increasing the root partition size by 50 MB).
